"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from centralconfig.v1 import audit_service_pb2 as _audit_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AuditServiceStub:
    """AuditService provides read-only access to the change history and usage
    statistics for tenant configurations.

    Write events are recorded automatically by the ConfigService whenever
    configuration values are modified (atomically with the config change).
    Usage statistics are tracked asynchronously via batched read counters.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AuditServiceAsyncStub: ...
    QueryWriteLog: _grpc.UnaryUnaryMultiCallable[_audit_service_pb2.QueryWriteLogRequest, _audit_service_pb2.QueryWriteLogResponse]
    """QueryWriteLog searches the audit log for config change events.
    All filter parameters are optional — omit a filter to match all values.
    """
    GetFieldUsage: _grpc.UnaryUnaryMultiCallable[_audit_service_pb2.GetFieldUsageRequest, _audit_service_pb2.GetFieldUsageResponse]
    """GetFieldUsage returns aggregated read statistics for a specific field."""
    GetTenantUsage: _grpc.UnaryUnaryMultiCallable[_audit_service_pb2.GetTenantUsageRequest, _audit_service_pb2.GetTenantUsageResponse]
    """GetTenantUsage returns aggregated read statistics for all fields of a tenant."""
    GetUnusedFields: _grpc.UnaryUnaryMultiCallable[_audit_service_pb2.GetUnusedFieldsRequest, _audit_service_pb2.GetUnusedFieldsResponse]
    """GetUnusedFields returns field paths that have not been read since the given time.
    Useful for identifying configuration fields that may be safe to deprecate.
    """

@_typing.type_check_only
class AuditServiceAsyncStub(AuditServiceStub):
    """AuditService provides read-only access to the change history and usage
    statistics for tenant configurations.

    Write events are recorded automatically by the ConfigService whenever
    configuration values are modified (atomically with the config change).
    Usage statistics are tracked asynchronously via batched read counters.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    QueryWriteLog: _aio.UnaryUnaryMultiCallable[_audit_service_pb2.QueryWriteLogRequest, _audit_service_pb2.QueryWriteLogResponse]  # type: ignore[assignment]
    """QueryWriteLog searches the audit log for config change events.
    All filter parameters are optional — omit a filter to match all values.
    """
    GetFieldUsage: _aio.UnaryUnaryMultiCallable[_audit_service_pb2.GetFieldUsageRequest, _audit_service_pb2.GetFieldUsageResponse]  # type: ignore[assignment]
    """GetFieldUsage returns aggregated read statistics for a specific field."""
    GetTenantUsage: _aio.UnaryUnaryMultiCallable[_audit_service_pb2.GetTenantUsageRequest, _audit_service_pb2.GetTenantUsageResponse]  # type: ignore[assignment]
    """GetTenantUsage returns aggregated read statistics for all fields of a tenant."""
    GetUnusedFields: _aio.UnaryUnaryMultiCallable[_audit_service_pb2.GetUnusedFieldsRequest, _audit_service_pb2.GetUnusedFieldsResponse]  # type: ignore[assignment]
    """GetUnusedFields returns field paths that have not been read since the given time.
    Useful for identifying configuration fields that may be safe to deprecate.
    """

class AuditServiceServicer(metaclass=_abc_1.ABCMeta):
    """AuditService provides read-only access to the change history and usage
    statistics for tenant configurations.

    Write events are recorded automatically by the ConfigService whenever
    configuration values are modified (atomically with the config change).
    Usage statistics are tracked asynchronously via batched read counters.
    """

    @_abc_1.abstractmethod
    def QueryWriteLog(
        self,
        request: _audit_service_pb2.QueryWriteLogRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_audit_service_pb2.QueryWriteLogResponse, _abc.Awaitable[_audit_service_pb2.QueryWriteLogResponse]]:
        """QueryWriteLog searches the audit log for config change events.
        All filter parameters are optional — omit a filter to match all values.
        """

    @_abc_1.abstractmethod
    def GetFieldUsage(
        self,
        request: _audit_service_pb2.GetFieldUsageRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_audit_service_pb2.GetFieldUsageResponse, _abc.Awaitable[_audit_service_pb2.GetFieldUsageResponse]]:
        """GetFieldUsage returns aggregated read statistics for a specific field."""

    @_abc_1.abstractmethod
    def GetTenantUsage(
        self,
        request: _audit_service_pb2.GetTenantUsageRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_audit_service_pb2.GetTenantUsageResponse, _abc.Awaitable[_audit_service_pb2.GetTenantUsageResponse]]:
        """GetTenantUsage returns aggregated read statistics for all fields of a tenant."""

    @_abc_1.abstractmethod
    def GetUnusedFields(
        self,
        request: _audit_service_pb2.GetUnusedFieldsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_audit_service_pb2.GetUnusedFieldsResponse, _abc.Awaitable[_audit_service_pb2.GetUnusedFieldsResponse]]:
        """GetUnusedFields returns field paths that have not been read since the given time.
        Useful for identifying configuration fields that may be safe to deprecate.
        """

def add_AuditServiceServicer_to_server(servicer: AuditServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
