# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from centralconfig.v1 import audit_service_pb2 as centralconfig_dot_v1_dot_audit__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in centralconfig/v1/audit_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditServiceStub(object):
    """AuditService provides read-only access to the change history and usage
    statistics for tenant configurations.

    Write events are recorded automatically by the ConfigService whenever
    configuration values are modified (atomically with the config change).
    Usage statistics are tracked asynchronously via batched read counters.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryWriteLog = channel.unary_unary(
                '/centralconfig.v1.AuditService/QueryWriteLog',
                request_serializer=centralconfig_dot_v1_dot_audit__service__pb2.QueryWriteLogRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_audit__service__pb2.QueryWriteLogResponse.FromString,
                _registered_method=True)
        self.GetFieldUsage = channel.unary_unary(
                '/centralconfig.v1.AuditService/GetFieldUsage',
                request_serializer=centralconfig_dot_v1_dot_audit__service__pb2.GetFieldUsageRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_audit__service__pb2.GetFieldUsageResponse.FromString,
                _registered_method=True)
        self.GetTenantUsage = channel.unary_unary(
                '/centralconfig.v1.AuditService/GetTenantUsage',
                request_serializer=centralconfig_dot_v1_dot_audit__service__pb2.GetTenantUsageRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_audit__service__pb2.GetTenantUsageResponse.FromString,
                _registered_method=True)
        self.GetUnusedFields = channel.unary_unary(
                '/centralconfig.v1.AuditService/GetUnusedFields',
                request_serializer=centralconfig_dot_v1_dot_audit__service__pb2.GetUnusedFieldsRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_audit__service__pb2.GetUnusedFieldsResponse.FromString,
                _registered_method=True)


class AuditServiceServicer(object):
    """AuditService provides read-only access to the change history and usage
    statistics for tenant configurations.

    Write events are recorded automatically by the ConfigService whenever
    configuration values are modified (atomically with the config change).
    Usage statistics are tracked asynchronously via batched read counters.
    """

    def QueryWriteLog(self, request, context):
        """QueryWriteLog searches the audit log for config change events.
        All filter parameters are optional — omit a filter to match all values.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFieldUsage(self, request, context):
        """GetFieldUsage returns aggregated read statistics for a specific field.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenantUsage(self, request, context):
        """GetTenantUsage returns aggregated read statistics for all fields of a tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnusedFields(self, request, context):
        """GetUnusedFields returns field paths that have not been read since the given time.
        Useful for identifying configuration fields that may be safe to deprecate.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryWriteLog': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryWriteLog,
                    request_deserializer=centralconfig_dot_v1_dot_audit__service__pb2.QueryWriteLogRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_audit__service__pb2.QueryWriteLogResponse.SerializeToString,
            ),
            'GetFieldUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFieldUsage,
                    request_deserializer=centralconfig_dot_v1_dot_audit__service__pb2.GetFieldUsageRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_audit__service__pb2.GetFieldUsageResponse.SerializeToString,
            ),
            'GetTenantUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantUsage,
                    request_deserializer=centralconfig_dot_v1_dot_audit__service__pb2.GetTenantUsageRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_audit__service__pb2.GetTenantUsageResponse.SerializeToString,
            ),
            'GetUnusedFields': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnusedFields,
                    request_deserializer=centralconfig_dot_v1_dot_audit__service__pb2.GetUnusedFieldsRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_audit__service__pb2.GetUnusedFieldsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'centralconfig.v1.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('centralconfig.v1.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService(object):
    """AuditService provides read-only access to the change history and usage
    statistics for tenant configurations.

    Write events are recorded automatically by the ConfigService whenever
    configuration values are modified (atomically with the config change).
    Usage statistics are tracked asynchronously via batched read counters.
    """

    @staticmethod
    def QueryWriteLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.AuditService/QueryWriteLog',
            centralconfig_dot_v1_dot_audit__service__pb2.QueryWriteLogRequest.SerializeToString,
            centralconfig_dot_v1_dot_audit__service__pb2.QueryWriteLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFieldUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.AuditService/GetFieldUsage',
            centralconfig_dot_v1_dot_audit__service__pb2.GetFieldUsageRequest.SerializeToString,
            centralconfig_dot_v1_dot_audit__service__pb2.GetFieldUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTenantUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.AuditService/GetTenantUsage',
            centralconfig_dot_v1_dot_audit__service__pb2.GetTenantUsageRequest.SerializeToString,
            centralconfig_dot_v1_dot_audit__service__pb2.GetTenantUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnusedFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.AuditService/GetUnusedFields',
            centralconfig_dot_v1_dot_audit__service__pb2.GetUnusedFieldsRequest.SerializeToString,
            centralconfig_dot_v1_dot_audit__service__pb2.GetUnusedFieldsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
