"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from centralconfig.v1 import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class QueryWriteLogRequest(_message.Message):
    """--- Write log queries ---"""

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    FIELD_PATH_FIELD_NUMBER: _builtins.int
    START_TIME_FIELD_NUMBER: _builtins.int
    END_TIME_FIELD_NUMBER: _builtins.int
    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Filter by tenant ID (UUID). If omitted, returns entries across all tenants."""
    actor: _builtins.str
    """Filter by actor (JWT subject). If omitted, matches all actors."""
    field_path: _builtins.str
    """Filter by field path. If omitted, matches all fields."""
    page_size: _builtins.int
    """Maximum number of results to return. Defaults to 50, max 100."""
    page_token: _builtins.str
    """Pagination token from a previous QueryWriteLogResponse."""
    @_builtins.property
    def start_time(self) -> _timestamp_pb2.Timestamp:
        """Filter entries created at or after this time. If omitted, no lower bound."""

    @_builtins.property
    def end_time(self) -> _timestamp_pb2.Timestamp:
        """Filter entries created at or before this time. If omitted, no upper bound."""

    def __init__(
        self,
        *,
        tenant_id: _builtins.str | None = ...,
        actor: _builtins.str | None = ...,
        field_path: _builtins.str | None = ...,
        start_time: _timestamp_pb2.Timestamp | None = ...,
        end_time: _timestamp_pb2.Timestamp | None = ...,
        page_size: _builtins.int = ...,
        page_token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_actor", b"_actor", "_end_time", b"_end_time", "_field_path", b"_field_path", "_start_time", b"_start_time", "_tenant_id", b"_tenant_id", "actor", b"actor", "end_time", b"end_time", "field_path", b"field_path", "start_time", b"start_time", "tenant_id", b"tenant_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_actor", b"_actor", "_end_time", b"_end_time", "_field_path", b"_field_path", "_start_time", b"_start_time", "_tenant_id", b"_tenant_id", "actor", b"actor", "end_time", b"end_time", "field_path", b"field_path", "page_size", b"page_size", "page_token", b"page_token", "start_time", b"start_time", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__actor: _TypeAlias = _typing.Literal["actor"]  # noqa: Y015
    _WhichOneofArgType__actor: _TypeAlias = _typing.Literal["_actor", b"_actor"]  # noqa: Y015
    _WhichOneofReturnType__end_time: _TypeAlias = _typing.Literal["end_time"]  # noqa: Y015
    _WhichOneofArgType__end_time: _TypeAlias = _typing.Literal["_end_time", b"_end_time"]  # noqa: Y015
    _WhichOneofReturnType__field_path: _TypeAlias = _typing.Literal["field_path"]  # noqa: Y015
    _WhichOneofArgType__field_path: _TypeAlias = _typing.Literal["_field_path", b"_field_path"]  # noqa: Y015
    _WhichOneofReturnType__start_time: _TypeAlias = _typing.Literal["start_time"]  # noqa: Y015
    _WhichOneofArgType__start_time: _TypeAlias = _typing.Literal["_start_time", b"_start_time"]  # noqa: Y015
    _WhichOneofReturnType__tenant_id: _TypeAlias = _typing.Literal["tenant_id"]  # noqa: Y015
    _WhichOneofArgType__tenant_id: _TypeAlias = _typing.Literal["_tenant_id", b"_tenant_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__actor) -> _WhichOneofReturnType__actor | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__end_time) -> _WhichOneofReturnType__end_time | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__field_path) -> _WhichOneofReturnType__field_path | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__start_time) -> _WhichOneofReturnType__start_time | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__tenant_id) -> _WhichOneofReturnType__tenant_id | None: ...

Global___QueryWriteLogRequest: _TypeAlias = QueryWriteLogRequest  # noqa: Y015

@_typing.final
class QueryWriteLogResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: _builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    next_page_token: _builtins.str
    """Token for the next page. Empty if no more results."""
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.AuditEntry]:
        """Audit entries matching the filters, ordered by created_at descending."""

    def __init__(
        self,
        *,
        entries: _abc.Iterable[_types_pb2.AuditEntry] | None = ...,
        next_page_token: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries", "next_page_token", b"next_page_token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryWriteLogResponse: _TypeAlias = QueryWriteLogResponse  # noqa: Y015

@_typing.final
class GetFieldUsageRequest(_message.Message):
    """--- Usage queries ---"""

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    FIELD_PATH_FIELD_NUMBER: _builtins.int
    START_TIME_FIELD_NUMBER: _builtins.int
    END_TIME_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    field_path: _builtins.str
    """Dot-separated field path to query."""
    @_builtins.property
    def start_time(self) -> _timestamp_pb2.Timestamp:
        """Start of the time range. If omitted, includes all historical data."""

    @_builtins.property
    def end_time(self) -> _timestamp_pb2.Timestamp:
        """End of the time range. If omitted, includes up to the current time."""

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        field_path: _builtins.str = ...,
        start_time: _timestamp_pb2.Timestamp | None = ...,
        end_time: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_end_time", b"_end_time", "_start_time", b"_start_time", "end_time", b"end_time", "start_time", b"start_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_end_time", b"_end_time", "_start_time", b"_start_time", "end_time", b"end_time", "field_path", b"field_path", "start_time", b"start_time", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__end_time: _TypeAlias = _typing.Literal["end_time"]  # noqa: Y015
    _WhichOneofArgType__end_time: _TypeAlias = _typing.Literal["_end_time", b"_end_time"]  # noqa: Y015
    _WhichOneofReturnType__start_time: _TypeAlias = _typing.Literal["start_time"]  # noqa: Y015
    _WhichOneofArgType__start_time: _TypeAlias = _typing.Literal["_start_time", b"_start_time"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__end_time) -> _WhichOneofReturnType__end_time | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__start_time) -> _WhichOneofReturnType__start_time | None: ...

Global___GetFieldUsageRequest: _TypeAlias = GetFieldUsageRequest  # noqa: Y015

@_typing.final
class GetFieldUsageResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stats(self) -> _types_pb2.UsageStats:
        """Aggregated usage statistics across the queried time range."""

    def __init__(
        self,
        *,
        stats: _types_pb2.UsageStats | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stats", b"stats"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stats", b"stats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetFieldUsageResponse: _TypeAlias = GetFieldUsageResponse  # noqa: Y015

@_typing.final
class GetTenantUsageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    START_TIME_FIELD_NUMBER: _builtins.int
    END_TIME_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    @_builtins.property
    def start_time(self) -> _timestamp_pb2.Timestamp:
        """Start of the time range. If omitted, includes all historical data."""

    @_builtins.property
    def end_time(self) -> _timestamp_pb2.Timestamp:
        """End of the time range. If omitted, includes up to the current time."""

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        start_time: _timestamp_pb2.Timestamp | None = ...,
        end_time: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_end_time", b"_end_time", "_start_time", b"_start_time", "end_time", b"end_time", "start_time", b"start_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_end_time", b"_end_time", "_start_time", b"_start_time", "end_time", b"end_time", "start_time", b"start_time", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__end_time: _TypeAlias = _typing.Literal["end_time"]  # noqa: Y015
    _WhichOneofArgType__end_time: _TypeAlias = _typing.Literal["_end_time", b"_end_time"]  # noqa: Y015
    _WhichOneofReturnType__start_time: _TypeAlias = _typing.Literal["start_time"]  # noqa: Y015
    _WhichOneofArgType__start_time: _TypeAlias = _typing.Literal["_start_time", b"_start_time"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__end_time) -> _WhichOneofReturnType__end_time | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__start_time) -> _WhichOneofReturnType__start_time | None: ...

Global___GetTenantUsageRequest: _TypeAlias = GetTenantUsageRequest  # noqa: Y015

@_typing.final
class GetTenantUsageResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FIELD_STATS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def field_stats(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.UsageStats]:
        """Per-field usage statistics, ordered by field path."""

    def __init__(
        self,
        *,
        field_stats: _abc.Iterable[_types_pb2.UsageStats] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["field_stats", b"field_stats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetTenantUsageResponse: _TypeAlias = GetTenantUsageResponse  # noqa: Y015

@_typing.final
class GetUnusedFieldsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    SINCE_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    @_builtins.property
    def since(self) -> _timestamp_pb2.Timestamp:
        """Fields not read since this time are considered unused.
        Required — there is no "all time" default to avoid expensive full scans.
        """

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        since: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["since", b"since"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["since", b"since", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetUnusedFieldsRequest: _TypeAlias = GetUnusedFieldsRequest  # noqa: Y015

@_typing.final
class GetUnusedFieldsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FIELD_PATHS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def field_paths(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Dot-separated paths of fields with no reads since the specified time."""

    def __init__(
        self,
        *,
        field_paths: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["field_paths", b"field_paths"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetUnusedFieldsResponse: _TypeAlias = GetUnusedFieldsResponse  # noqa: Y015
