"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from centralconfig.v1 import config_service_pb2 as _config_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ConfigServiceStub:
    """ConfigService manages configuration values, versions, and real-time subscriptions.

    Configuration is stored per-tenant using delta versioning: each write creates a
    new version containing only the changed fields. The full config at any version is
    the union of all deltas up to that version (latest value per field wins).

    Read operations are cached in Redis. Write operations are atomic: the config
    version, values, and audit log entry are committed in a single database transaction.
    Read operations.
    Reads are served from Redis cache when possible. Setting include_descriptions
    bypasses the cache and reads directly from the database.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ConfigServiceAsyncStub: ...
    GetConfig: _grpc.UnaryUnaryMultiCallable[_config_service_pb2.GetConfigRequest, _config_service_pb2.GetConfigResponse]
    """GetConfig returns the full resolved configuration for a tenant."""
    GetField: _grpc.UnaryUnaryMultiCallable[_config_service_pb2.GetFieldRequest, _config_service_pb2.GetFieldResponse]
    """GetField returns a single configuration value by field path."""
    GetFields: _grpc.UnaryUnaryMultiCallable[_config_service_pb2.GetFieldsRequest, _config_service_pb2.GetFieldsResponse]
    """GetFields returns multiple configuration values by field paths.
    Fields that don't exist are silently omitted from the response.
    """
    SetField: _grpc.UnaryUnaryMultiCallable[_config_service_pb2.SetFieldRequest, _config_service_pb2.SetFieldResponse]
    """Write operations.
    Each write creates a new config version atomically with its audit log entry.
    Cache is invalidated and change events are published after the transaction commits.

    SetField sets a single configuration value, creating a new config version.
    """
    SetFields: _grpc.UnaryUnaryMultiCallable[_config_service_pb2.SetFieldsRequest, _config_service_pb2.SetFieldsResponse]
    """SetFields sets multiple configuration values in a single config version."""
    ListVersions: _grpc.UnaryUnaryMultiCallable[_config_service_pb2.ListVersionsRequest, _config_service_pb2.ListVersionsResponse]
    """Version operations.

    ListVersions returns config version history for a tenant (newest first).
    """
    GetVersion: _grpc.UnaryUnaryMultiCallable[_config_service_pb2.GetVersionRequest, _config_service_pb2.GetVersionResponse]
    """GetVersion retrieves metadata for a specific config version."""
    RollbackToVersion: _grpc.UnaryUnaryMultiCallable[_config_service_pb2.RollbackToVersionRequest, _config_service_pb2.RollbackToVersionResponse]
    """RollbackToVersion creates a new version with the same values as the target version.
    This does not delete intermediate versions — it creates a new version that
    copies the target's values.
    """
    Subscribe: _grpc.UnaryStreamMultiCallable[_config_service_pb2.SubscribeRequest, _config_service_pb2.SubscribeResponse]
    """Real-time subscriptions via server-streaming.

    Subscribe opens a server-streaming connection that pushes ConfigChange events
    whenever the tenant's configuration is modified. The stream remains open until
    the client disconnects or the server shuts down.
    """
    ExportConfig: _grpc.UnaryUnaryMultiCallable[_config_service_pb2.ExportConfigRequest, _config_service_pb2.ExportConfigResponse]
    """Import/export.

    ExportConfig serializes a tenant's configuration to YAML.
    """
    ImportConfig: _grpc.UnaryUnaryMultiCallable[_config_service_pb2.ImportConfigRequest, _config_service_pb2.ImportConfigResponse]
    """ImportConfig applies configuration values from YAML."""

@_typing.type_check_only
class ConfigServiceAsyncStub(ConfigServiceStub):
    """ConfigService manages configuration values, versions, and real-time subscriptions.

    Configuration is stored per-tenant using delta versioning: each write creates a
    new version containing only the changed fields. The full config at any version is
    the union of all deltas up to that version (latest value per field wins).

    Read operations are cached in Redis. Write operations are atomic: the config
    version, values, and audit log entry are committed in a single database transaction.
    Read operations.
    Reads are served from Redis cache when possible. Setting include_descriptions
    bypasses the cache and reads directly from the database.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetConfig: _aio.UnaryUnaryMultiCallable[_config_service_pb2.GetConfigRequest, _config_service_pb2.GetConfigResponse]  # type: ignore[assignment]
    """GetConfig returns the full resolved configuration for a tenant."""
    GetField: _aio.UnaryUnaryMultiCallable[_config_service_pb2.GetFieldRequest, _config_service_pb2.GetFieldResponse]  # type: ignore[assignment]
    """GetField returns a single configuration value by field path."""
    GetFields: _aio.UnaryUnaryMultiCallable[_config_service_pb2.GetFieldsRequest, _config_service_pb2.GetFieldsResponse]  # type: ignore[assignment]
    """GetFields returns multiple configuration values by field paths.
    Fields that don't exist are silently omitted from the response.
    """
    SetField: _aio.UnaryUnaryMultiCallable[_config_service_pb2.SetFieldRequest, _config_service_pb2.SetFieldResponse]  # type: ignore[assignment]
    """Write operations.
    Each write creates a new config version atomically with its audit log entry.
    Cache is invalidated and change events are published after the transaction commits.

    SetField sets a single configuration value, creating a new config version.
    """
    SetFields: _aio.UnaryUnaryMultiCallable[_config_service_pb2.SetFieldsRequest, _config_service_pb2.SetFieldsResponse]  # type: ignore[assignment]
    """SetFields sets multiple configuration values in a single config version."""
    ListVersions: _aio.UnaryUnaryMultiCallable[_config_service_pb2.ListVersionsRequest, _config_service_pb2.ListVersionsResponse]  # type: ignore[assignment]
    """Version operations.

    ListVersions returns config version history for a tenant (newest first).
    """
    GetVersion: _aio.UnaryUnaryMultiCallable[_config_service_pb2.GetVersionRequest, _config_service_pb2.GetVersionResponse]  # type: ignore[assignment]
    """GetVersion retrieves metadata for a specific config version."""
    RollbackToVersion: _aio.UnaryUnaryMultiCallable[_config_service_pb2.RollbackToVersionRequest, _config_service_pb2.RollbackToVersionResponse]  # type: ignore[assignment]
    """RollbackToVersion creates a new version with the same values as the target version.
    This does not delete intermediate versions — it creates a new version that
    copies the target's values.
    """
    Subscribe: _aio.UnaryStreamMultiCallable[_config_service_pb2.SubscribeRequest, _config_service_pb2.SubscribeResponse]  # type: ignore[assignment]
    """Real-time subscriptions via server-streaming.

    Subscribe opens a server-streaming connection that pushes ConfigChange events
    whenever the tenant's configuration is modified. The stream remains open until
    the client disconnects or the server shuts down.
    """
    ExportConfig: _aio.UnaryUnaryMultiCallable[_config_service_pb2.ExportConfigRequest, _config_service_pb2.ExportConfigResponse]  # type: ignore[assignment]
    """Import/export.

    ExportConfig serializes a tenant's configuration to YAML.
    """
    ImportConfig: _aio.UnaryUnaryMultiCallable[_config_service_pb2.ImportConfigRequest, _config_service_pb2.ImportConfigResponse]  # type: ignore[assignment]
    """ImportConfig applies configuration values from YAML."""

class ConfigServiceServicer(metaclass=_abc_1.ABCMeta):
    """ConfigService manages configuration values, versions, and real-time subscriptions.

    Configuration is stored per-tenant using delta versioning: each write creates a
    new version containing only the changed fields. The full config at any version is
    the union of all deltas up to that version (latest value per field wins).

    Read operations are cached in Redis. Write operations are atomic: the config
    version, values, and audit log entry are committed in a single database transaction.
    Read operations.
    Reads are served from Redis cache when possible. Setting include_descriptions
    bypasses the cache and reads directly from the database.
    """

    @_abc_1.abstractmethod
    def GetConfig(
        self,
        request: _config_service_pb2.GetConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_config_service_pb2.GetConfigResponse, _abc.Awaitable[_config_service_pb2.GetConfigResponse]]:
        """GetConfig returns the full resolved configuration for a tenant."""

    @_abc_1.abstractmethod
    def GetField(
        self,
        request: _config_service_pb2.GetFieldRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_config_service_pb2.GetFieldResponse, _abc.Awaitable[_config_service_pb2.GetFieldResponse]]:
        """GetField returns a single configuration value by field path."""

    @_abc_1.abstractmethod
    def GetFields(
        self,
        request: _config_service_pb2.GetFieldsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_config_service_pb2.GetFieldsResponse, _abc.Awaitable[_config_service_pb2.GetFieldsResponse]]:
        """GetFields returns multiple configuration values by field paths.
        Fields that don't exist are silently omitted from the response.
        """

    @_abc_1.abstractmethod
    def SetField(
        self,
        request: _config_service_pb2.SetFieldRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_config_service_pb2.SetFieldResponse, _abc.Awaitable[_config_service_pb2.SetFieldResponse]]:
        """Write operations.
        Each write creates a new config version atomically with its audit log entry.
        Cache is invalidated and change events are published after the transaction commits.

        SetField sets a single configuration value, creating a new config version.
        """

    @_abc_1.abstractmethod
    def SetFields(
        self,
        request: _config_service_pb2.SetFieldsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_config_service_pb2.SetFieldsResponse, _abc.Awaitable[_config_service_pb2.SetFieldsResponse]]:
        """SetFields sets multiple configuration values in a single config version."""

    @_abc_1.abstractmethod
    def ListVersions(
        self,
        request: _config_service_pb2.ListVersionsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_config_service_pb2.ListVersionsResponse, _abc.Awaitable[_config_service_pb2.ListVersionsResponse]]:
        """Version operations.

        ListVersions returns config version history for a tenant (newest first).
        """

    @_abc_1.abstractmethod
    def GetVersion(
        self,
        request: _config_service_pb2.GetVersionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_config_service_pb2.GetVersionResponse, _abc.Awaitable[_config_service_pb2.GetVersionResponse]]:
        """GetVersion retrieves metadata for a specific config version."""

    @_abc_1.abstractmethod
    def RollbackToVersion(
        self,
        request: _config_service_pb2.RollbackToVersionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_config_service_pb2.RollbackToVersionResponse, _abc.Awaitable[_config_service_pb2.RollbackToVersionResponse]]:
        """RollbackToVersion creates a new version with the same values as the target version.
        This does not delete intermediate versions — it creates a new version that
        copies the target's values.
        """

    @_abc_1.abstractmethod
    def Subscribe(
        self,
        request: _config_service_pb2.SubscribeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_config_service_pb2.SubscribeResponse], _abc.AsyncIterator[_config_service_pb2.SubscribeResponse]]:
        """Real-time subscriptions via server-streaming.

        Subscribe opens a server-streaming connection that pushes ConfigChange events
        whenever the tenant's configuration is modified. The stream remains open until
        the client disconnects or the server shuts down.
        """

    @_abc_1.abstractmethod
    def ExportConfig(
        self,
        request: _config_service_pb2.ExportConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_config_service_pb2.ExportConfigResponse, _abc.Awaitable[_config_service_pb2.ExportConfigResponse]]:
        """Import/export.

        ExportConfig serializes a tenant's configuration to YAML.
        """

    @_abc_1.abstractmethod
    def ImportConfig(
        self,
        request: _config_service_pb2.ImportConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_config_service_pb2.ImportConfigResponse, _abc.Awaitable[_config_service_pb2.ImportConfigResponse]]:
        """ImportConfig applies configuration values from YAML."""

def add_ConfigServiceServicer_to_server(servicer: ConfigServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
