# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from centralconfig.v1 import config_service_pb2 as centralconfig_dot_v1_dot_config__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in centralconfig/v1/config_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConfigServiceStub(object):
    """ConfigService manages configuration values, versions, and real-time subscriptions.

    Configuration is stored per-tenant using delta versioning: each write creates a
    new version containing only the changed fields. The full config at any version is
    the union of all deltas up to that version (latest value per field wins).

    Read operations are cached in Redis. Write operations are atomic: the config
    version, values, and audit log entry are committed in a single database transaction.
    Read operations.
    Reads are served from Redis cache when possible. Setting include_descriptions
    bypasses the cache and reads directly from the database.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfig = channel.unary_unary(
                '/centralconfig.v1.ConfigService/GetConfig',
                request_serializer=centralconfig_dot_v1_dot_config__service__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_config__service__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.GetField = channel.unary_unary(
                '/centralconfig.v1.ConfigService/GetField',
                request_serializer=centralconfig_dot_v1_dot_config__service__pb2.GetFieldRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_config__service__pb2.GetFieldResponse.FromString,
                _registered_method=True)
        self.GetFields = channel.unary_unary(
                '/centralconfig.v1.ConfigService/GetFields',
                request_serializer=centralconfig_dot_v1_dot_config__service__pb2.GetFieldsRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_config__service__pb2.GetFieldsResponse.FromString,
                _registered_method=True)
        self.SetField = channel.unary_unary(
                '/centralconfig.v1.ConfigService/SetField',
                request_serializer=centralconfig_dot_v1_dot_config__service__pb2.SetFieldRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_config__service__pb2.SetFieldResponse.FromString,
                _registered_method=True)
        self.SetFields = channel.unary_unary(
                '/centralconfig.v1.ConfigService/SetFields',
                request_serializer=centralconfig_dot_v1_dot_config__service__pb2.SetFieldsRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_config__service__pb2.SetFieldsResponse.FromString,
                _registered_method=True)
        self.ListVersions = channel.unary_unary(
                '/centralconfig.v1.ConfigService/ListVersions',
                request_serializer=centralconfig_dot_v1_dot_config__service__pb2.ListVersionsRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_config__service__pb2.ListVersionsResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/centralconfig.v1.ConfigService/GetVersion',
                request_serializer=centralconfig_dot_v1_dot_config__service__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_config__service__pb2.GetVersionResponse.FromString,
                _registered_method=True)
        self.RollbackToVersion = channel.unary_unary(
                '/centralconfig.v1.ConfigService/RollbackToVersion',
                request_serializer=centralconfig_dot_v1_dot_config__service__pb2.RollbackToVersionRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_config__service__pb2.RollbackToVersionResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/centralconfig.v1.ConfigService/Subscribe',
                request_serializer=centralconfig_dot_v1_dot_config__service__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_config__service__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.ExportConfig = channel.unary_unary(
                '/centralconfig.v1.ConfigService/ExportConfig',
                request_serializer=centralconfig_dot_v1_dot_config__service__pb2.ExportConfigRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_config__service__pb2.ExportConfigResponse.FromString,
                _registered_method=True)
        self.ImportConfig = channel.unary_unary(
                '/centralconfig.v1.ConfigService/ImportConfig',
                request_serializer=centralconfig_dot_v1_dot_config__service__pb2.ImportConfigRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_config__service__pb2.ImportConfigResponse.FromString,
                _registered_method=True)


class ConfigServiceServicer(object):
    """ConfigService manages configuration values, versions, and real-time subscriptions.

    Configuration is stored per-tenant using delta versioning: each write creates a
    new version containing only the changed fields. The full config at any version is
    the union of all deltas up to that version (latest value per field wins).

    Read operations are cached in Redis. Write operations are atomic: the config
    version, values, and audit log entry are committed in a single database transaction.
    Read operations.
    Reads are served from Redis cache when possible. Setting include_descriptions
    bypasses the cache and reads directly from the database.
    """

    def GetConfig(self, request, context):
        """GetConfig returns the full resolved configuration for a tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetField(self, request, context):
        """GetField returns a single configuration value by field path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFields(self, request, context):
        """GetFields returns multiple configuration values by field paths.
        Fields that don't exist are silently omitted from the response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetField(self, request, context):
        """Write operations.
        Each write creates a new config version atomically with its audit log entry.
        Cache is invalidated and change events are published after the transaction commits.

        SetField sets a single configuration value, creating a new config version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFields(self, request, context):
        """SetFields sets multiple configuration values in a single config version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVersions(self, request, context):
        """Version operations.

        ListVersions returns config version history for a tenant (newest first).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """GetVersion retrieves metadata for a specific config version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackToVersion(self, request, context):
        """RollbackToVersion creates a new version with the same values as the target version.
        This does not delete intermediate versions — it creates a new version that
        copies the target's values.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Real-time subscriptions via server-streaming.

        Subscribe opens a server-streaming connection that pushes ConfigChange events
        whenever the tenant's configuration is modified. The stream remains open until
        the client disconnects or the server shuts down.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportConfig(self, request, context):
        """Import/export.

        ExportConfig serializes a tenant's configuration to YAML.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportConfig(self, request, context):
        """ImportConfig applies configuration values from YAML.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=centralconfig_dot_v1_dot_config__service__pb2.GetConfigRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_config__service__pb2.GetConfigResponse.SerializeToString,
            ),
            'GetField': grpc.unary_unary_rpc_method_handler(
                    servicer.GetField,
                    request_deserializer=centralconfig_dot_v1_dot_config__service__pb2.GetFieldRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_config__service__pb2.GetFieldResponse.SerializeToString,
            ),
            'GetFields': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFields,
                    request_deserializer=centralconfig_dot_v1_dot_config__service__pb2.GetFieldsRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_config__service__pb2.GetFieldsResponse.SerializeToString,
            ),
            'SetField': grpc.unary_unary_rpc_method_handler(
                    servicer.SetField,
                    request_deserializer=centralconfig_dot_v1_dot_config__service__pb2.SetFieldRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_config__service__pb2.SetFieldResponse.SerializeToString,
            ),
            'SetFields': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFields,
                    request_deserializer=centralconfig_dot_v1_dot_config__service__pb2.SetFieldsRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_config__service__pb2.SetFieldsResponse.SerializeToString,
            ),
            'ListVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVersions,
                    request_deserializer=centralconfig_dot_v1_dot_config__service__pb2.ListVersionsRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_config__service__pb2.ListVersionsResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=centralconfig_dot_v1_dot_config__service__pb2.GetVersionRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_config__service__pb2.GetVersionResponse.SerializeToString,
            ),
            'RollbackToVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackToVersion,
                    request_deserializer=centralconfig_dot_v1_dot_config__service__pb2.RollbackToVersionRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_config__service__pb2.RollbackToVersionResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=centralconfig_dot_v1_dot_config__service__pb2.SubscribeRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_config__service__pb2.SubscribeResponse.SerializeToString,
            ),
            'ExportConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportConfig,
                    request_deserializer=centralconfig_dot_v1_dot_config__service__pb2.ExportConfigRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_config__service__pb2.ExportConfigResponse.SerializeToString,
            ),
            'ImportConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportConfig,
                    request_deserializer=centralconfig_dot_v1_dot_config__service__pb2.ImportConfigRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_config__service__pb2.ImportConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'centralconfig.v1.ConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('centralconfig.v1.ConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigService(object):
    """ConfigService manages configuration values, versions, and real-time subscriptions.

    Configuration is stored per-tenant using delta versioning: each write creates a
    new version containing only the changed fields. The full config at any version is
    the union of all deltas up to that version (latest value per field wins).

    Read operations are cached in Redis. Write operations are atomic: the config
    version, values, and audit log entry are committed in a single database transaction.
    Read operations.
    Reads are served from Redis cache when possible. Setting include_descriptions
    bypasses the cache and reads directly from the database.
    """

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.ConfigService/GetConfig',
            centralconfig_dot_v1_dot_config__service__pb2.GetConfigRequest.SerializeToString,
            centralconfig_dot_v1_dot_config__service__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.ConfigService/GetField',
            centralconfig_dot_v1_dot_config__service__pb2.GetFieldRequest.SerializeToString,
            centralconfig_dot_v1_dot_config__service__pb2.GetFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.ConfigService/GetFields',
            centralconfig_dot_v1_dot_config__service__pb2.GetFieldsRequest.SerializeToString,
            centralconfig_dot_v1_dot_config__service__pb2.GetFieldsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.ConfigService/SetField',
            centralconfig_dot_v1_dot_config__service__pb2.SetFieldRequest.SerializeToString,
            centralconfig_dot_v1_dot_config__service__pb2.SetFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.ConfigService/SetFields',
            centralconfig_dot_v1_dot_config__service__pb2.SetFieldsRequest.SerializeToString,
            centralconfig_dot_v1_dot_config__service__pb2.SetFieldsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.ConfigService/ListVersions',
            centralconfig_dot_v1_dot_config__service__pb2.ListVersionsRequest.SerializeToString,
            centralconfig_dot_v1_dot_config__service__pb2.ListVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.ConfigService/GetVersion',
            centralconfig_dot_v1_dot_config__service__pb2.GetVersionRequest.SerializeToString,
            centralconfig_dot_v1_dot_config__service__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackToVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.ConfigService/RollbackToVersion',
            centralconfig_dot_v1_dot_config__service__pb2.RollbackToVersionRequest.SerializeToString,
            centralconfig_dot_v1_dot_config__service__pb2.RollbackToVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/centralconfig.v1.ConfigService/Subscribe',
            centralconfig_dot_v1_dot_config__service__pb2.SubscribeRequest.SerializeToString,
            centralconfig_dot_v1_dot_config__service__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.ConfigService/ExportConfig',
            centralconfig_dot_v1_dot_config__service__pb2.ExportConfigRequest.SerializeToString,
            centralconfig_dot_v1_dot_config__service__pb2.ExportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.ConfigService/ImportConfig',
            centralconfig_dot_v1_dot_config__service__pb2.ImportConfigRequest.SerializeToString,
            centralconfig_dot_v1_dot_config__service__pb2.ImportConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
