"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from centralconfig.v1 import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _ImportMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ImportModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ImportMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    IMPORT_MODE_UNSPECIFIED: _ImportMode.ValueType  # 0
    """Unspecified defaults to merge behavior."""
    IMPORT_MODE_MERGE: _ImportMode.ValueType  # 1
    """Merge: update fields from YAML that differ, keep runtime overrides
    for fields not in the YAML.
    """
    IMPORT_MODE_REPLACE: _ImportMode.ValueType  # 2
    """Replace: full replace — all fields from YAML are set, fields not in YAML
    are not carried forward. Runtime overrides are wiped.
    """
    IMPORT_MODE_DEFAULTS: _ImportMode.ValueType  # 3
    """Defaults: only set fields that have no value yet. Fields that already have
    a value are skipped regardless of the YAML content.
    """

class ImportMode(_ImportMode, metaclass=_ImportModeEnumTypeWrapper):
    """ImportMode controls how imported values interact with existing config."""

IMPORT_MODE_UNSPECIFIED: ImportMode.ValueType  # 0
"""Unspecified defaults to merge behavior."""
IMPORT_MODE_MERGE: ImportMode.ValueType  # 1
"""Merge: update fields from YAML that differ, keep runtime overrides
for fields not in the YAML.
"""
IMPORT_MODE_REPLACE: ImportMode.ValueType  # 2
"""Replace: full replace — all fields from YAML are set, fields not in YAML
are not carried forward. Runtime overrides are wiped.
"""
IMPORT_MODE_DEFAULTS: ImportMode.ValueType  # 3
"""Defaults: only set fields that have no value yet. Fields that already have
a value are skipped regardless of the YAML content.
"""
Global___ImportMode: _TypeAlias = ImportMode  # noqa: Y015

@_typing.final
class GetConfigRequest(_message.Message):
    """--- Read requests/responses ---"""

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    INCLUDE_DESCRIPTIONS_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    version: _builtins.int
    """Config version to retrieve. If omitted, returns the latest version."""
    include_descriptions: _builtins.bool
    """When true, includes value-level descriptions in the response.
    This bypasses the Redis cache and reads directly from the database.
    """
    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        version: _builtins.int | None = ...,
        include_descriptions: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "include_descriptions", b"include_descriptions", "tenant_id", b"tenant_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__version: _TypeAlias = _typing.Literal["version"]  # noqa: Y015
    _WhichOneofArgType__version: _TypeAlias = _typing.Literal["_version", b"_version"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__version) -> _WhichOneofReturnType__version | None: ...

Global___GetConfigRequest: _TypeAlias = GetConfigRequest  # noqa: Y015

@_typing.final
class GetConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config(self) -> _types_pb2.Config:
        """The full resolved configuration at the requested version."""

    def __init__(
        self,
        *,
        config: _types_pb2.Config | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetConfigResponse: _TypeAlias = GetConfigResponse  # noqa: Y015

@_typing.final
class GetFieldRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    FIELD_PATH_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    INCLUDE_DESCRIPTION_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    field_path: _builtins.str
    """Dot-separated field path (e.g. "payments.fee")."""
    version: _builtins.int
    """Config version to read from. If omitted, reads from the latest version."""
    include_description: _builtins.bool
    """When true, includes the value-level description.
    This bypasses the Redis cache and reads directly from the database.
    """
    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        field_path: _builtins.str = ...,
        version: _builtins.int | None = ...,
        include_description: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "field_path", b"field_path", "include_description", b"include_description", "tenant_id", b"tenant_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__version: _TypeAlias = _typing.Literal["version"]  # noqa: Y015
    _WhichOneofArgType__version: _TypeAlias = _typing.Literal["_version", b"_version"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__version) -> _WhichOneofReturnType__version | None: ...

Global___GetFieldRequest: _TypeAlias = GetFieldRequest  # noqa: Y015

@_typing.final
class GetFieldResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def value(self) -> _types_pb2.ConfigValue:
        """The configuration value. Returns NOT_FOUND if the field has no value set."""

    def __init__(
        self,
        *,
        value: _types_pb2.ConfigValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetFieldResponse: _TypeAlias = GetFieldResponse  # noqa: Y015

@_typing.final
class GetFieldsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    FIELD_PATHS_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    INCLUDE_DESCRIPTIONS_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    version: _builtins.int
    """Config version to read from. If omitted, reads from the latest version."""
    include_descriptions: _builtins.bool
    """When true, includes value-level descriptions.
    This bypasses the Redis cache and reads directly from the database.
    """
    @_builtins.property
    def field_paths(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Dot-separated field paths to retrieve."""

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        field_paths: _abc.Iterable[_builtins.str] | None = ...,
        version: _builtins.int | None = ...,
        include_descriptions: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "field_paths", b"field_paths", "include_descriptions", b"include_descriptions", "tenant_id", b"tenant_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__version: _TypeAlias = _typing.Literal["version"]  # noqa: Y015
    _WhichOneofArgType__version: _TypeAlias = _typing.Literal["_version", b"_version"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__version) -> _WhichOneofReturnType__version | None: ...

Global___GetFieldsRequest: _TypeAlias = GetFieldsRequest  # noqa: Y015

@_typing.final
class GetFieldsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.ConfigValue]:
        """The requested values. Fields that don't exist are omitted (not an error)."""

    def __init__(
        self,
        *,
        values: _abc.Iterable[_types_pb2.ConfigValue] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetFieldsResponse: _TypeAlias = GetFieldsResponse  # noqa: Y015

@_typing.final
class SetFieldRequest(_message.Message):
    """--- Write requests/responses ---"""

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    FIELD_PATH_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    EXPECTED_CHECKSUM_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    VALUE_DESCRIPTION_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    field_path: _builtins.str
    """Dot-separated field path (e.g. "payments.fee")."""
    expected_checksum: _builtins.str
    """Optimistic concurrency control: the checksum from a previous GetField/GetConfig
    response. If provided and the field's current checksum doesn't match, the
    request fails with ABORTED. This prevents lost updates when multiple actors
    modify the same field concurrently.
    """
    description: _builtins.str
    """Version-level description explaining why this change was made."""
    value_description: _builtins.str
    """Value-level description explaining what this specific value means.
    Retrievable via include_description in read requests.
    """
    @_builtins.property
    def value(self) -> _types_pb2.TypedValue:
        """The typed value. Omit to set the field to null."""

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        field_path: _builtins.str = ...,
        value: _types_pb2.TypedValue | None = ...,
        expected_checksum: _builtins.str | None = ...,
        description: _builtins.str | None = ...,
        value_description: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "_expected_checksum", b"_expected_checksum", "_value_description", b"_value_description", "description", b"description", "expected_checksum", b"expected_checksum", "value", b"value", "value_description", b"value_description"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "_expected_checksum", b"_expected_checksum", "_value_description", b"_value_description", "description", b"description", "expected_checksum", b"expected_checksum", "field_path", b"field_path", "tenant_id", b"tenant_id", "value", b"value", "value_description", b"value_description"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    _WhichOneofReturnType__expected_checksum: _TypeAlias = _typing.Literal["expected_checksum"]  # noqa: Y015
    _WhichOneofArgType__expected_checksum: _TypeAlias = _typing.Literal["_expected_checksum", b"_expected_checksum"]  # noqa: Y015
    _WhichOneofReturnType__value_description: _TypeAlias = _typing.Literal["value_description"]  # noqa: Y015
    _WhichOneofArgType__value_description: _TypeAlias = _typing.Literal["_value_description", b"_value_description"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__expected_checksum) -> _WhichOneofReturnType__expected_checksum | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__value_description) -> _WhichOneofReturnType__value_description | None: ...

Global___SetFieldRequest: _TypeAlias = SetFieldRequest  # noqa: Y015

@_typing.final
class SetFieldResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_VERSION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config_version(self) -> _types_pb2.ConfigVersion:
        """The newly created config version."""

    def __init__(
        self,
        *,
        config_version: _types_pb2.ConfigVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config_version", b"config_version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_version", b"config_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetFieldResponse: _TypeAlias = SetFieldResponse  # noqa: Y015

@_typing.final
class SetFieldsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    UPDATES_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    description: _builtins.str
    """Version-level description explaining why these changes were made."""
    @_builtins.property
    def updates(self) -> _containers.RepeatedCompositeFieldContainer[Global___FieldUpdate]:
        """Field updates to apply. All updates are applied atomically in a single
        config version. If any update fails validation (checksum, field lock),
        no changes are committed.
        """

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        updates: _abc.Iterable[Global___FieldUpdate] | None = ...,
        description: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description", "tenant_id", b"tenant_id", "updates", b"updates"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...

Global___SetFieldsRequest: _TypeAlias = SetFieldsRequest  # noqa: Y015

@_typing.final
class SetFieldsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_VERSION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config_version(self) -> _types_pb2.ConfigVersion:
        """The newly created config version."""

    def __init__(
        self,
        *,
        config_version: _types_pb2.ConfigVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config_version", b"config_version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_version", b"config_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetFieldsResponse: _TypeAlias = SetFieldsResponse  # noqa: Y015

@_typing.final
class FieldUpdate(_message.Message):
    """FieldUpdate represents a single field change within a SetFields batch."""

    DESCRIPTOR: _descriptor.Descriptor

    FIELD_PATH_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    EXPECTED_CHECKSUM_FIELD_NUMBER: _builtins.int
    VALUE_DESCRIPTION_FIELD_NUMBER: _builtins.int
    field_path: _builtins.str
    """Dot-separated field path."""
    expected_checksum: _builtins.str
    """Optimistic concurrency control checksum for this specific field.
    See SetFieldRequest.expected_checksum for details.
    """
    value_description: _builtins.str
    """Value-level description for this specific field."""
    @_builtins.property
    def value(self) -> _types_pb2.TypedValue:
        """The typed value. Omit to set the field to null."""

    def __init__(
        self,
        *,
        field_path: _builtins.str = ...,
        value: _types_pb2.TypedValue | None = ...,
        expected_checksum: _builtins.str | None = ...,
        value_description: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_expected_checksum", b"_expected_checksum", "_value_description", b"_value_description", "expected_checksum", b"expected_checksum", "value", b"value", "value_description", b"value_description"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_expected_checksum", b"_expected_checksum", "_value_description", b"_value_description", "expected_checksum", b"expected_checksum", "field_path", b"field_path", "value", b"value", "value_description", b"value_description"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__expected_checksum: _TypeAlias = _typing.Literal["expected_checksum"]  # noqa: Y015
    _WhichOneofArgType__expected_checksum: _TypeAlias = _typing.Literal["_expected_checksum", b"_expected_checksum"]  # noqa: Y015
    _WhichOneofReturnType__value_description: _TypeAlias = _typing.Literal["value_description"]  # noqa: Y015
    _WhichOneofArgType__value_description: _TypeAlias = _typing.Literal["_value_description", b"_value_description"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__expected_checksum) -> _WhichOneofReturnType__expected_checksum | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__value_description) -> _WhichOneofReturnType__value_description | None: ...

Global___FieldUpdate: _TypeAlias = FieldUpdate  # noqa: Y015

@_typing.final
class ListVersionsRequest(_message.Message):
    """--- Version requests/responses ---"""

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    page_size: _builtins.int
    """Maximum number of results to return. Defaults to 50, max 100."""
    page_token: _builtins.str
    """Pagination token from a previous ListVersionsResponse."""
    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        page_size: _builtins.int = ...,
        page_token: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["page_size", b"page_size", "page_token", b"page_token", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListVersionsRequest: _TypeAlias = ListVersionsRequest  # noqa: Y015

@_typing.final
class ListVersionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSIONS_FIELD_NUMBER: _builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    next_page_token: _builtins.str
    """Token for the next page. Empty if no more results."""
    @_builtins.property
    def versions(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.ConfigVersion]:
        """Config versions, ordered by version number descending (newest first)."""

    def __init__(
        self,
        *,
        versions: _abc.Iterable[_types_pb2.ConfigVersion] | None = ...,
        next_page_token: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["next_page_token", b"next_page_token", "versions", b"versions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListVersionsResponse: _TypeAlias = ListVersionsResponse  # noqa: Y015

@_typing.final
class GetVersionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    version: _builtins.int
    """The version number to retrieve."""
    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        version: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tenant_id", b"tenant_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetVersionRequest: _TypeAlias = GetVersionRequest  # noqa: Y015

@_typing.final
class GetVersionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_VERSION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config_version(self) -> _types_pb2.ConfigVersion: ...
    def __init__(
        self,
        *,
        config_version: _types_pb2.ConfigVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config_version", b"config_version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_version", b"config_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetVersionResponse: _TypeAlias = GetVersionResponse  # noqa: Y015

@_typing.final
class RollbackToVersionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    version: _builtins.int
    """The target version to rollback to. The full config at this version
    is copied into a new version (the current version number + 1).
    The target version itself is not modified.
    """
    description: _builtins.str
    """Description for the new rollback version. Defaults to
    "Rollback to version N" if omitted.
    """
    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        version: _builtins.int = ...,
        description: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description", "tenant_id", b"tenant_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...

Global___RollbackToVersionRequest: _TypeAlias = RollbackToVersionRequest  # noqa: Y015

@_typing.final
class RollbackToVersionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_VERSION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config_version(self) -> _types_pb2.ConfigVersion:
        """The newly created config version containing the rolled-back values."""

    def __init__(
        self,
        *,
        config_version: _types_pb2.ConfigVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config_version", b"config_version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_version", b"config_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RollbackToVersionResponse: _TypeAlias = RollbackToVersionResponse  # noqa: Y015

@_typing.final
class SubscribeRequest(_message.Message):
    """--- Subscription ---"""

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    FIELD_PATHS_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID) to subscribe to."""
    @_builtins.property
    def field_paths(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Field paths to filter on. If empty, receives changes for all fields.
        Changes to fields not in this list are silently dropped.
        """

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        field_paths: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["field_paths", b"field_paths", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeRequest: _TypeAlias = SubscribeRequest  # noqa: Y015

@_typing.final
class SubscribeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHANGE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def change(self) -> _types_pb2.ConfigChange:
        """A configuration change event. Delivered via Redis Pub/Sub internally."""

    def __init__(
        self,
        *,
        change: _types_pb2.ConfigChange | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["change", b"change"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["change", b"change"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeResponse: _TypeAlias = SubscribeResponse  # noqa: Y015

@_typing.final
class ExportConfigRequest(_message.Message):
    """--- Import/export ---"""

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    version: _builtins.int
    """Config version to export. If omitted, exports the latest version."""
    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        version: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "tenant_id", b"tenant_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__version: _TypeAlias = _typing.Literal["version"]  # noqa: Y015
    _WhichOneofArgType__version: _TypeAlias = _typing.Literal["_version", b"_version"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__version) -> _WhichOneofReturnType__version | None: ...

Global___ExportConfigRequest: _TypeAlias = ExportConfigRequest  # noqa: Y015

@_typing.final
class ExportConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    YAML_CONTENT_FIELD_NUMBER: _builtins.int
    yaml_content: _builtins.bytes
    """YAML-encoded configuration values."""
    def __init__(
        self,
        *,
        yaml_content: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["yaml_content", b"yaml_content"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExportConfigResponse: _TypeAlias = ExportConfigResponse  # noqa: Y015

@_typing.final
class ImportConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    YAML_CONTENT_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    yaml_content: _builtins.bytes
    """YAML-encoded configuration values to import."""
    description: _builtins.str
    """Description for the new config version created by the import."""
    mode: Global___ImportMode.ValueType
    """Import mode. Defaults to IMPORT_MODE_MERGE."""
    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        yaml_content: _builtins.bytes = ...,
        description: _builtins.str | None = ...,
        mode: Global___ImportMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description", "mode", b"mode", "tenant_id", b"tenant_id", "yaml_content", b"yaml_content"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...

Global___ImportConfigRequest: _TypeAlias = ImportConfigRequest  # noqa: Y015

@_typing.final
class ImportConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_VERSION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config_version(self) -> _types_pb2.ConfigVersion:
        """The config version created by the import."""

    def __init__(
        self,
        *,
        config_version: _types_pb2.ConfigVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config_version", b"config_version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_version", b"config_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ImportConfigResponse: _TypeAlias = ImportConfigResponse  # noqa: Y015
