# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from centralconfig.v1 import schema_service_pb2 as centralconfig_dot_v1_dot_schema__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in centralconfig/v1/schema_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchemaServiceStub(object):
    """SchemaService manages configuration schemas, tenants, and field-level locking.

    Schemas define the allowed fields and their types for tenant configurations.
    Each schema is versioned — updates create new immutable versions that must be
    published before tenants can use them.
    Schema lifecycle.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSchema = channel.unary_unary(
                '/centralconfig.v1.SchemaService/CreateSchema',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.CreateSchemaRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.CreateSchemaResponse.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/centralconfig.v1.SchemaService/GetSchema',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.GetSchemaResponse.FromString,
                _registered_method=True)
        self.ListSchemas = channel.unary_unary(
                '/centralconfig.v1.SchemaService/ListSchemas',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.ListSchemasRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.ListSchemasResponse.FromString,
                _registered_method=True)
        self.UpdateSchema = channel.unary_unary(
                '/centralconfig.v1.SchemaService/UpdateSchema',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.UpdateSchemaRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.UpdateSchemaResponse.FromString,
                _registered_method=True)
        self.DeleteSchema = channel.unary_unary(
                '/centralconfig.v1.SchemaService/DeleteSchema',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.DeleteSchemaRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.DeleteSchemaResponse.FromString,
                _registered_method=True)
        self.PublishSchema = channel.unary_unary(
                '/centralconfig.v1.SchemaService/PublishSchema',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.PublishSchemaRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.PublishSchemaResponse.FromString,
                _registered_method=True)
        self.CreateTenant = channel.unary_unary(
                '/centralconfig.v1.SchemaService/CreateTenant',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.CreateTenantRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.CreateTenantResponse.FromString,
                _registered_method=True)
        self.GetTenant = channel.unary_unary(
                '/centralconfig.v1.SchemaService/GetTenant',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.GetTenantRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.GetTenantResponse.FromString,
                _registered_method=True)
        self.ListTenants = channel.unary_unary(
                '/centralconfig.v1.SchemaService/ListTenants',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.ListTenantsRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.ListTenantsResponse.FromString,
                _registered_method=True)
        self.UpdateTenant = channel.unary_unary(
                '/centralconfig.v1.SchemaService/UpdateTenant',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.UpdateTenantRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.UpdateTenantResponse.FromString,
                _registered_method=True)
        self.DeleteTenant = channel.unary_unary(
                '/centralconfig.v1.SchemaService/DeleteTenant',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.DeleteTenantRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.DeleteTenantResponse.FromString,
                _registered_method=True)
        self.LockField = channel.unary_unary(
                '/centralconfig.v1.SchemaService/LockField',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.LockFieldRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.LockFieldResponse.FromString,
                _registered_method=True)
        self.UnlockField = channel.unary_unary(
                '/centralconfig.v1.SchemaService/UnlockField',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.UnlockFieldRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.UnlockFieldResponse.FromString,
                _registered_method=True)
        self.ListFieldLocks = channel.unary_unary(
                '/centralconfig.v1.SchemaService/ListFieldLocks',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.ListFieldLocksRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.ListFieldLocksResponse.FromString,
                _registered_method=True)
        self.ExportSchema = channel.unary_unary(
                '/centralconfig.v1.SchemaService/ExportSchema',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.ExportSchemaRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.ExportSchemaResponse.FromString,
                _registered_method=True)
        self.ImportSchema = channel.unary_unary(
                '/centralconfig.v1.SchemaService/ImportSchema',
                request_serializer=centralconfig_dot_v1_dot_schema__service__pb2.ImportSchemaRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.ImportSchemaResponse.FromString,
                _registered_method=True)


class SchemaServiceServicer(object):
    """SchemaService manages configuration schemas, tenants, and field-level locking.

    Schemas define the allowed fields and their types for tenant configurations.
    Each schema is versioned — updates create new immutable versions that must be
    published before tenants can use them.
    Schema lifecycle.
    """

    def CreateSchema(self, request, context):
        """CreateSchema creates a new schema with an initial draft version (v1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """GetSchema retrieves a schema by ID, optionally at a specific version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchemas(self, request, context):
        """ListSchemas returns all schemas, ordered by creation time (newest first).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSchema(self, request, context):
        """UpdateSchema creates a new draft version by merging field changes with the latest version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchema(self, request, context):
        """DeleteSchema permanently deletes a schema and all its versions. Cascades to tenants.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishSchema(self, request, context):
        """PublishSchema marks a schema version as published and immutable.
        Only published versions can be assigned to tenants.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTenant(self, request, context):
        """Tenant lifecycle.

        CreateTenant creates a new tenant assigned to a published schema version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenant(self, request, context):
        """GetTenant retrieves a tenant by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTenants(self, request, context):
        """ListTenants returns tenants, optionally filtered by schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTenant(self, request, context):
        """UpdateTenant updates a tenant's name or upgrades its schema version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTenant(self, request, context):
        """DeleteTenant permanently deletes a tenant and all its configuration data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockField(self, request, context):
        """Field locking.
        Locked fields cannot be modified by admin or user roles.
        Superadmins bypass all field locks.

        LockField prevents a field from being modified.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockField(self, request, context):
        """UnlockField removes a field lock, allowing modifications again.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFieldLocks(self, request, context):
        """ListFieldLocks returns all active field locks for a tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportSchema(self, request, context):
        """Import/export.
        Schemas can be exported as YAML (syntax v1) for backup, review, or version control.

        ExportSchema serializes a schema version to YAML.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportSchema(self, request, context):
        """ImportSchema creates a schema (or new version) from YAML.
        Full-replace semantics: the YAML defines the complete field set.
        Returns AlreadyExists if the imported fields are identical to the latest version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchemaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchema,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.CreateSchemaRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.CreateSchemaResponse.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.GetSchemaRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.GetSchemaResponse.SerializeToString,
            ),
            'ListSchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchemas,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.ListSchemasRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.ListSchemasResponse.SerializeToString,
            ),
            'UpdateSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSchema,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.UpdateSchemaRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.UpdateSchemaResponse.SerializeToString,
            ),
            'DeleteSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchema,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.DeleteSchemaRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.DeleteSchemaResponse.SerializeToString,
            ),
            'PublishSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishSchema,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.PublishSchemaRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.PublishSchemaResponse.SerializeToString,
            ),
            'CreateTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTenant,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.CreateTenantRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.CreateTenantResponse.SerializeToString,
            ),
            'GetTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenant,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.GetTenantRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.GetTenantResponse.SerializeToString,
            ),
            'ListTenants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTenants,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.ListTenantsRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.ListTenantsResponse.SerializeToString,
            ),
            'UpdateTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTenant,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.UpdateTenantRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.UpdateTenantResponse.SerializeToString,
            ),
            'DeleteTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTenant,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.DeleteTenantRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.DeleteTenantResponse.SerializeToString,
            ),
            'LockField': grpc.unary_unary_rpc_method_handler(
                    servicer.LockField,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.LockFieldRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.LockFieldResponse.SerializeToString,
            ),
            'UnlockField': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockField,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.UnlockFieldRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.UnlockFieldResponse.SerializeToString,
            ),
            'ListFieldLocks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFieldLocks,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.ListFieldLocksRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.ListFieldLocksResponse.SerializeToString,
            ),
            'ExportSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportSchema,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.ExportSchemaRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.ExportSchemaResponse.SerializeToString,
            ),
            'ImportSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportSchema,
                    request_deserializer=centralconfig_dot_v1_dot_schema__service__pb2.ImportSchemaRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_schema__service__pb2.ImportSchemaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'centralconfig.v1.SchemaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('centralconfig.v1.SchemaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchemaService(object):
    """SchemaService manages configuration schemas, tenants, and field-level locking.

    Schemas define the allowed fields and their types for tenant configurations.
    Each schema is versioned — updates create new immutable versions that must be
    published before tenants can use them.
    Schema lifecycle.
    """

    @staticmethod
    def CreateSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/CreateSchema',
            centralconfig_dot_v1_dot_schema__service__pb2.CreateSchemaRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.CreateSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/GetSchema',
            centralconfig_dot_v1_dot_schema__service__pb2.GetSchemaRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/ListSchemas',
            centralconfig_dot_v1_dot_schema__service__pb2.ListSchemasRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.ListSchemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/UpdateSchema',
            centralconfig_dot_v1_dot_schema__service__pb2.UpdateSchemaRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.UpdateSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/DeleteSchema',
            centralconfig_dot_v1_dot_schema__service__pb2.DeleteSchemaRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.DeleteSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/PublishSchema',
            centralconfig_dot_v1_dot_schema__service__pb2.PublishSchemaRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.PublishSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/CreateTenant',
            centralconfig_dot_v1_dot_schema__service__pb2.CreateTenantRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.CreateTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/GetTenant',
            centralconfig_dot_v1_dot_schema__service__pb2.GetTenantRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.GetTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTenants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/ListTenants',
            centralconfig_dot_v1_dot_schema__service__pb2.ListTenantsRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.ListTenantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/UpdateTenant',
            centralconfig_dot_v1_dot_schema__service__pb2.UpdateTenantRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.UpdateTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/DeleteTenant',
            centralconfig_dot_v1_dot_schema__service__pb2.DeleteTenantRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.DeleteTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LockField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/LockField',
            centralconfig_dot_v1_dot_schema__service__pb2.LockFieldRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.LockFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/UnlockField',
            centralconfig_dot_v1_dot_schema__service__pb2.UnlockFieldRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.UnlockFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFieldLocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/ListFieldLocks',
            centralconfig_dot_v1_dot_schema__service__pb2.ListFieldLocksRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.ListFieldLocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/ExportSchema',
            centralconfig_dot_v1_dot_schema__service__pb2.ExportSchemaRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.ExportSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.SchemaService/ImportSchema',
            centralconfig_dot_v1_dot_schema__service__pb2.ImportSchemaRequest.SerializeToString,
            centralconfig_dot_v1_dot_schema__service__pb2.ImportSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
