"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from centralconfig.v1 import schema_service_pb2 as _schema_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class SchemaServiceStub:
    """SchemaService manages configuration schemas, tenants, and field-level locking.

    Schemas define the allowed fields and their types for tenant configurations.
    Each schema is versioned — updates create new immutable versions that must be
    published before tenants can use them.
    Schema lifecycle.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> SchemaServiceAsyncStub: ...
    CreateSchema: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.CreateSchemaRequest, _schema_service_pb2.CreateSchemaResponse]
    """CreateSchema creates a new schema with an initial draft version (v1)."""
    GetSchema: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.GetSchemaRequest, _schema_service_pb2.GetSchemaResponse]
    """GetSchema retrieves a schema by ID, optionally at a specific version."""
    ListSchemas: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.ListSchemasRequest, _schema_service_pb2.ListSchemasResponse]
    """ListSchemas returns all schemas, ordered by creation time (newest first)."""
    UpdateSchema: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.UpdateSchemaRequest, _schema_service_pb2.UpdateSchemaResponse]
    """UpdateSchema creates a new draft version by merging field changes with the latest version."""
    DeleteSchema: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.DeleteSchemaRequest, _schema_service_pb2.DeleteSchemaResponse]
    """DeleteSchema permanently deletes a schema and all its versions. Cascades to tenants."""
    PublishSchema: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.PublishSchemaRequest, _schema_service_pb2.PublishSchemaResponse]
    """PublishSchema marks a schema version as published and immutable.
    Only published versions can be assigned to tenants.
    """
    CreateTenant: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.CreateTenantRequest, _schema_service_pb2.CreateTenantResponse]
    """Tenant lifecycle.

    CreateTenant creates a new tenant assigned to a published schema version.
    """
    GetTenant: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.GetTenantRequest, _schema_service_pb2.GetTenantResponse]
    """GetTenant retrieves a tenant by ID."""
    ListTenants: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.ListTenantsRequest, _schema_service_pb2.ListTenantsResponse]
    """ListTenants returns tenants, optionally filtered by schema."""
    UpdateTenant: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.UpdateTenantRequest, _schema_service_pb2.UpdateTenantResponse]
    """UpdateTenant updates a tenant's name or upgrades its schema version."""
    DeleteTenant: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.DeleteTenantRequest, _schema_service_pb2.DeleteTenantResponse]
    """DeleteTenant permanently deletes a tenant and all its configuration data."""
    LockField: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.LockFieldRequest, _schema_service_pb2.LockFieldResponse]
    """Field locking.
    Locked fields cannot be modified by admin or user roles.
    Superadmins bypass all field locks.

    LockField prevents a field from being modified.
    """
    UnlockField: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.UnlockFieldRequest, _schema_service_pb2.UnlockFieldResponse]
    """UnlockField removes a field lock, allowing modifications again."""
    ListFieldLocks: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.ListFieldLocksRequest, _schema_service_pb2.ListFieldLocksResponse]
    """ListFieldLocks returns all active field locks for a tenant."""
    ExportSchema: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.ExportSchemaRequest, _schema_service_pb2.ExportSchemaResponse]
    """Import/export.
    Schemas can be exported as YAML (syntax v1) for backup, review, or version control.

    ExportSchema serializes a schema version to YAML.
    """
    ImportSchema: _grpc.UnaryUnaryMultiCallable[_schema_service_pb2.ImportSchemaRequest, _schema_service_pb2.ImportSchemaResponse]
    """ImportSchema creates a schema (or new version) from YAML.
    Full-replace semantics: the YAML defines the complete field set.
    Returns AlreadyExists if the imported fields are identical to the latest version.
    """

@_typing.type_check_only
class SchemaServiceAsyncStub(SchemaServiceStub):
    """SchemaService manages configuration schemas, tenants, and field-level locking.

    Schemas define the allowed fields and their types for tenant configurations.
    Each schema is versioned — updates create new immutable versions that must be
    published before tenants can use them.
    Schema lifecycle.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    CreateSchema: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.CreateSchemaRequest, _schema_service_pb2.CreateSchemaResponse]  # type: ignore[assignment]
    """CreateSchema creates a new schema with an initial draft version (v1)."""
    GetSchema: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.GetSchemaRequest, _schema_service_pb2.GetSchemaResponse]  # type: ignore[assignment]
    """GetSchema retrieves a schema by ID, optionally at a specific version."""
    ListSchemas: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.ListSchemasRequest, _schema_service_pb2.ListSchemasResponse]  # type: ignore[assignment]
    """ListSchemas returns all schemas, ordered by creation time (newest first)."""
    UpdateSchema: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.UpdateSchemaRequest, _schema_service_pb2.UpdateSchemaResponse]  # type: ignore[assignment]
    """UpdateSchema creates a new draft version by merging field changes with the latest version."""
    DeleteSchema: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.DeleteSchemaRequest, _schema_service_pb2.DeleteSchemaResponse]  # type: ignore[assignment]
    """DeleteSchema permanently deletes a schema and all its versions. Cascades to tenants."""
    PublishSchema: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.PublishSchemaRequest, _schema_service_pb2.PublishSchemaResponse]  # type: ignore[assignment]
    """PublishSchema marks a schema version as published and immutable.
    Only published versions can be assigned to tenants.
    """
    CreateTenant: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.CreateTenantRequest, _schema_service_pb2.CreateTenantResponse]  # type: ignore[assignment]
    """Tenant lifecycle.

    CreateTenant creates a new tenant assigned to a published schema version.
    """
    GetTenant: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.GetTenantRequest, _schema_service_pb2.GetTenantResponse]  # type: ignore[assignment]
    """GetTenant retrieves a tenant by ID."""
    ListTenants: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.ListTenantsRequest, _schema_service_pb2.ListTenantsResponse]  # type: ignore[assignment]
    """ListTenants returns tenants, optionally filtered by schema."""
    UpdateTenant: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.UpdateTenantRequest, _schema_service_pb2.UpdateTenantResponse]  # type: ignore[assignment]
    """UpdateTenant updates a tenant's name or upgrades its schema version."""
    DeleteTenant: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.DeleteTenantRequest, _schema_service_pb2.DeleteTenantResponse]  # type: ignore[assignment]
    """DeleteTenant permanently deletes a tenant and all its configuration data."""
    LockField: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.LockFieldRequest, _schema_service_pb2.LockFieldResponse]  # type: ignore[assignment]
    """Field locking.
    Locked fields cannot be modified by admin or user roles.
    Superadmins bypass all field locks.

    LockField prevents a field from being modified.
    """
    UnlockField: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.UnlockFieldRequest, _schema_service_pb2.UnlockFieldResponse]  # type: ignore[assignment]
    """UnlockField removes a field lock, allowing modifications again."""
    ListFieldLocks: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.ListFieldLocksRequest, _schema_service_pb2.ListFieldLocksResponse]  # type: ignore[assignment]
    """ListFieldLocks returns all active field locks for a tenant."""
    ExportSchema: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.ExportSchemaRequest, _schema_service_pb2.ExportSchemaResponse]  # type: ignore[assignment]
    """Import/export.
    Schemas can be exported as YAML (syntax v1) for backup, review, or version control.

    ExportSchema serializes a schema version to YAML.
    """
    ImportSchema: _aio.UnaryUnaryMultiCallable[_schema_service_pb2.ImportSchemaRequest, _schema_service_pb2.ImportSchemaResponse]  # type: ignore[assignment]
    """ImportSchema creates a schema (or new version) from YAML.
    Full-replace semantics: the YAML defines the complete field set.
    Returns AlreadyExists if the imported fields are identical to the latest version.
    """

class SchemaServiceServicer(metaclass=_abc_1.ABCMeta):
    """SchemaService manages configuration schemas, tenants, and field-level locking.

    Schemas define the allowed fields and their types for tenant configurations.
    Each schema is versioned — updates create new immutable versions that must be
    published before tenants can use them.
    Schema lifecycle.
    """

    @_abc_1.abstractmethod
    def CreateSchema(
        self,
        request: _schema_service_pb2.CreateSchemaRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.CreateSchemaResponse, _abc.Awaitable[_schema_service_pb2.CreateSchemaResponse]]:
        """CreateSchema creates a new schema with an initial draft version (v1)."""

    @_abc_1.abstractmethod
    def GetSchema(
        self,
        request: _schema_service_pb2.GetSchemaRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.GetSchemaResponse, _abc.Awaitable[_schema_service_pb2.GetSchemaResponse]]:
        """GetSchema retrieves a schema by ID, optionally at a specific version."""

    @_abc_1.abstractmethod
    def ListSchemas(
        self,
        request: _schema_service_pb2.ListSchemasRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.ListSchemasResponse, _abc.Awaitable[_schema_service_pb2.ListSchemasResponse]]:
        """ListSchemas returns all schemas, ordered by creation time (newest first)."""

    @_abc_1.abstractmethod
    def UpdateSchema(
        self,
        request: _schema_service_pb2.UpdateSchemaRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.UpdateSchemaResponse, _abc.Awaitable[_schema_service_pb2.UpdateSchemaResponse]]:
        """UpdateSchema creates a new draft version by merging field changes with the latest version."""

    @_abc_1.abstractmethod
    def DeleteSchema(
        self,
        request: _schema_service_pb2.DeleteSchemaRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.DeleteSchemaResponse, _abc.Awaitable[_schema_service_pb2.DeleteSchemaResponse]]:
        """DeleteSchema permanently deletes a schema and all its versions. Cascades to tenants."""

    @_abc_1.abstractmethod
    def PublishSchema(
        self,
        request: _schema_service_pb2.PublishSchemaRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.PublishSchemaResponse, _abc.Awaitable[_schema_service_pb2.PublishSchemaResponse]]:
        """PublishSchema marks a schema version as published and immutable.
        Only published versions can be assigned to tenants.
        """

    @_abc_1.abstractmethod
    def CreateTenant(
        self,
        request: _schema_service_pb2.CreateTenantRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.CreateTenantResponse, _abc.Awaitable[_schema_service_pb2.CreateTenantResponse]]:
        """Tenant lifecycle.

        CreateTenant creates a new tenant assigned to a published schema version.
        """

    @_abc_1.abstractmethod
    def GetTenant(
        self,
        request: _schema_service_pb2.GetTenantRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.GetTenantResponse, _abc.Awaitable[_schema_service_pb2.GetTenantResponse]]:
        """GetTenant retrieves a tenant by ID."""

    @_abc_1.abstractmethod
    def ListTenants(
        self,
        request: _schema_service_pb2.ListTenantsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.ListTenantsResponse, _abc.Awaitable[_schema_service_pb2.ListTenantsResponse]]:
        """ListTenants returns tenants, optionally filtered by schema."""

    @_abc_1.abstractmethod
    def UpdateTenant(
        self,
        request: _schema_service_pb2.UpdateTenantRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.UpdateTenantResponse, _abc.Awaitable[_schema_service_pb2.UpdateTenantResponse]]:
        """UpdateTenant updates a tenant's name or upgrades its schema version."""

    @_abc_1.abstractmethod
    def DeleteTenant(
        self,
        request: _schema_service_pb2.DeleteTenantRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.DeleteTenantResponse, _abc.Awaitable[_schema_service_pb2.DeleteTenantResponse]]:
        """DeleteTenant permanently deletes a tenant and all its configuration data."""

    @_abc_1.abstractmethod
    def LockField(
        self,
        request: _schema_service_pb2.LockFieldRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.LockFieldResponse, _abc.Awaitable[_schema_service_pb2.LockFieldResponse]]:
        """Field locking.
        Locked fields cannot be modified by admin or user roles.
        Superadmins bypass all field locks.

        LockField prevents a field from being modified.
        """

    @_abc_1.abstractmethod
    def UnlockField(
        self,
        request: _schema_service_pb2.UnlockFieldRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.UnlockFieldResponse, _abc.Awaitable[_schema_service_pb2.UnlockFieldResponse]]:
        """UnlockField removes a field lock, allowing modifications again."""

    @_abc_1.abstractmethod
    def ListFieldLocks(
        self,
        request: _schema_service_pb2.ListFieldLocksRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.ListFieldLocksResponse, _abc.Awaitable[_schema_service_pb2.ListFieldLocksResponse]]:
        """ListFieldLocks returns all active field locks for a tenant."""

    @_abc_1.abstractmethod
    def ExportSchema(
        self,
        request: _schema_service_pb2.ExportSchemaRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.ExportSchemaResponse, _abc.Awaitable[_schema_service_pb2.ExportSchemaResponse]]:
        """Import/export.
        Schemas can be exported as YAML (syntax v1) for backup, review, or version control.

        ExportSchema serializes a schema version to YAML.
        """

    @_abc_1.abstractmethod
    def ImportSchema(
        self,
        request: _schema_service_pb2.ImportSchemaRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_schema_service_pb2.ImportSchemaResponse, _abc.Awaitable[_schema_service_pb2.ImportSchemaResponse]]:
        """ImportSchema creates a schema (or new version) from YAML.
        Full-replace semantics: the YAML defines the complete field set.
        Returns AlreadyExists if the imported fields are identical to the latest version.
        """

def add_SchemaServiceServicer_to_server(servicer: SchemaServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
