"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from centralconfig.v1 import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreateSchemaRequest(_message.Message):
    """--- Schema requests/responses ---"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    FIELDS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Unique name for the schema. Must be a valid slug: lowercase alphanumeric
    and hyphens, 1-63 characters (e.g. "payment-config", "settlement-rules").
    """
    description: _builtins.str
    """Human-readable description of the schema's purpose."""
    @_builtins.property
    def fields(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.SchemaField]:
        """Initial field definitions for version 1. At least one field is required."""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        description: _builtins.str | None = ...,
        fields: _abc.Iterable[_types_pb2.SchemaField] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description", "fields", b"fields", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...

Global___CreateSchemaRequest: _TypeAlias = CreateSchemaRequest  # noqa: Y015

@_typing.final
class CreateSchemaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCHEMA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def schema(self) -> _types_pb2.Schema:
        """The created schema with version 1 (draft, unpublished)."""

    def __init__(
        self,
        *,
        schema: _types_pb2.Schema | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateSchemaResponse: _TypeAlias = CreateSchemaResponse  # noqa: Y015

@_typing.final
class GetSchemaRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Schema ID (UUID)."""
    version: _builtins.int
    """Schema version to retrieve. If omitted, returns the latest version."""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        version: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "id", b"id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__version: _TypeAlias = _typing.Literal["version"]  # noqa: Y015
    _WhichOneofArgType__version: _TypeAlias = _typing.Literal["_version", b"_version"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__version) -> _WhichOneofReturnType__version | None: ...

Global___GetSchemaRequest: _TypeAlias = GetSchemaRequest  # noqa: Y015

@_typing.final
class GetSchemaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCHEMA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def schema(self) -> _types_pb2.Schema: ...
    def __init__(
        self,
        *,
        schema: _types_pb2.Schema | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetSchemaResponse: _TypeAlias = GetSchemaResponse  # noqa: Y015

@_typing.final
class ListSchemasRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FILTER_FIELD_NUMBER: _builtins.int
    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    name_filter: _builtins.str
    """Filter schemas by name prefix. Currently reserved for future use."""
    page_size: _builtins.int
    """Maximum number of results to return. Defaults to 50, max 100."""
    page_token: _builtins.str
    """Pagination token from a previous ListSchemasResponse."""
    def __init__(
        self,
        *,
        name_filter: _builtins.str | None = ...,
        page_size: _builtins.int = ...,
        page_token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_name_filter", b"_name_filter", "name_filter", b"name_filter"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_name_filter", b"_name_filter", "name_filter", b"name_filter", "page_size", b"page_size", "page_token", b"page_token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__name_filter: _TypeAlias = _typing.Literal["name_filter"]  # noqa: Y015
    _WhichOneofArgType__name_filter: _TypeAlias = _typing.Literal["_name_filter", b"_name_filter"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name_filter) -> _WhichOneofReturnType__name_filter | None: ...

Global___ListSchemasRequest: _TypeAlias = ListSchemasRequest  # noqa: Y015

@_typing.final
class ListSchemasResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCHEMAS_FIELD_NUMBER: _builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    next_page_token: _builtins.str
    """Token for the next page. Empty if no more results."""
    @_builtins.property
    def schemas(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.Schema]:
        """Schemas with their latest version."""

    def __init__(
        self,
        *,
        schemas: _abc.Iterable[_types_pb2.Schema] | None = ...,
        next_page_token: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["next_page_token", b"next_page_token", "schemas", b"schemas"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListSchemasResponse: _TypeAlias = ListSchemasResponse  # noqa: Y015

@_typing.final
class UpdateSchemaRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    VERSION_DESCRIPTION_FIELD_NUMBER: _builtins.int
    FIELDS_FIELD_NUMBER: _builtins.int
    REMOVE_FIELDS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Schema ID (UUID)."""
    version_description: _builtins.str
    """Description of what changed in this version."""
    @_builtins.property
    def fields(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.SchemaField]:
        """Fields to add or modify. Existing fields not listed here are carried
        forward unchanged from the latest version.
        """

    @_builtins.property
    def remove_fields(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Dot-separated paths of fields to remove from the new version."""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        version_description: _builtins.str | None = ...,
        fields: _abc.Iterable[_types_pb2.SchemaField] | None = ...,
        remove_fields: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_version_description", b"_version_description", "version_description", b"version_description"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_version_description", b"_version_description", "fields", b"fields", "id", b"id", "remove_fields", b"remove_fields", "version_description", b"version_description"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__version_description: _TypeAlias = _typing.Literal["version_description"]  # noqa: Y015
    _WhichOneofArgType__version_description: _TypeAlias = _typing.Literal["_version_description", b"_version_description"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__version_description) -> _WhichOneofReturnType__version_description | None: ...

Global___UpdateSchemaRequest: _TypeAlias = UpdateSchemaRequest  # noqa: Y015

@_typing.final
class UpdateSchemaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCHEMA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def schema(self) -> _types_pb2.Schema:
        """The new schema version (draft, unpublished)."""

    def __init__(
        self,
        *,
        schema: _types_pb2.Schema | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateSchemaResponse: _TypeAlias = UpdateSchemaResponse  # noqa: Y015

@_typing.final
class DeleteSchemaRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Schema ID (UUID). Cascades to all versions, fields, and associated tenants."""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteSchemaRequest: _TypeAlias = DeleteSchemaRequest  # noqa: Y015

@_typing.final
class DeleteSchemaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DeleteSchemaResponse: _TypeAlias = DeleteSchemaResponse  # noqa: Y015

@_typing.final
class PublishSchemaRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Schema ID (UUID)."""
    version: _builtins.int
    """The version number to publish. Must be an existing draft version.
    Once published, the version is immutable.
    """
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        version: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PublishSchemaRequest: _TypeAlias = PublishSchemaRequest  # noqa: Y015

@_typing.final
class PublishSchemaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCHEMA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def schema(self) -> _types_pb2.Schema:
        """The published schema version."""

    def __init__(
        self,
        *,
        schema: _types_pb2.Schema | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PublishSchemaResponse: _TypeAlias = PublishSchemaResponse  # noqa: Y015

@_typing.final
class CreateTenantRequest(_message.Message):
    """--- Tenant requests/responses ---"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    SCHEMA_ID_FIELD_NUMBER: _builtins.int
    SCHEMA_VERSION_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Unique name for the tenant. Must be a valid slug: lowercase alphanumeric
    and hyphens, 1-63 characters (e.g. "acme-corp", "tenant-42").
    """
    schema_id: _builtins.str
    """The schema to assign to this tenant (UUID)."""
    schema_version: _builtins.int
    """The schema version to use. Must be a published version."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        schema_id: _builtins.str = ...,
        schema_version: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "schema_id", b"schema_id", "schema_version", b"schema_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateTenantRequest: _TypeAlias = CreateTenantRequest  # noqa: Y015

@_typing.final
class CreateTenantResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tenant(self) -> _types_pb2.Tenant: ...
    def __init__(
        self,
        *,
        tenant: _types_pb2.Tenant | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["tenant", b"tenant"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tenant", b"tenant"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateTenantResponse: _TypeAlias = CreateTenantResponse  # noqa: Y015

@_typing.final
class GetTenantRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Tenant ID (UUID)."""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetTenantRequest: _TypeAlias = GetTenantRequest  # noqa: Y015

@_typing.final
class GetTenantResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tenant(self) -> _types_pb2.Tenant: ...
    def __init__(
        self,
        *,
        tenant: _types_pb2.Tenant | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["tenant", b"tenant"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tenant", b"tenant"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetTenantResponse: _TypeAlias = GetTenantResponse  # noqa: Y015

@_typing.final
class ListTenantsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCHEMA_ID_FIELD_NUMBER: _builtins.int
    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    schema_id: _builtins.str
    """Filter by schema ID (UUID). If omitted, returns tenants across all schemas."""
    page_size: _builtins.int
    """Maximum number of results to return. Defaults to 50, max 100."""
    page_token: _builtins.str
    """Pagination token from a previous ListTenantsResponse."""
    def __init__(
        self,
        *,
        schema_id: _builtins.str | None = ...,
        page_size: _builtins.int = ...,
        page_token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_schema_id", b"_schema_id", "schema_id", b"schema_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_schema_id", b"_schema_id", "page_size", b"page_size", "page_token", b"page_token", "schema_id", b"schema_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__schema_id: _TypeAlias = _typing.Literal["schema_id"]  # noqa: Y015
    _WhichOneofArgType__schema_id: _TypeAlias = _typing.Literal["_schema_id", b"_schema_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__schema_id) -> _WhichOneofReturnType__schema_id | None: ...

Global___ListTenantsRequest: _TypeAlias = ListTenantsRequest  # noqa: Y015

@_typing.final
class ListTenantsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANTS_FIELD_NUMBER: _builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    next_page_token: _builtins.str
    """Token for the next page. Empty if no more results."""
    @_builtins.property
    def tenants(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.Tenant]: ...
    def __init__(
        self,
        *,
        tenants: _abc.Iterable[_types_pb2.Tenant] | None = ...,
        next_page_token: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["next_page_token", b"next_page_token", "tenants", b"tenants"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListTenantsResponse: _TypeAlias = ListTenantsResponse  # noqa: Y015

@_typing.final
class UpdateTenantRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SCHEMA_VERSION_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Tenant ID (UUID)."""
    name: _builtins.str
    """New name for the tenant. Must be a valid slug if provided."""
    schema_version: _builtins.int
    """Upgrade to a new schema version. The new version must belong to the
    same schema and must be published.
    """
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str | None = ...,
        schema_version: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "_schema_version", b"_schema_version", "name", b"name", "schema_version", b"schema_version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "_schema_version", b"_schema_version", "id", b"id", "name", b"name", "schema_version", b"schema_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    _WhichOneofReturnType__schema_version: _TypeAlias = _typing.Literal["schema_version"]  # noqa: Y015
    _WhichOneofArgType__schema_version: _TypeAlias = _typing.Literal["_schema_version", b"_schema_version"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__schema_version) -> _WhichOneofReturnType__schema_version | None: ...

Global___UpdateTenantRequest: _TypeAlias = UpdateTenantRequest  # noqa: Y015

@_typing.final
class UpdateTenantResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tenant(self) -> _types_pb2.Tenant: ...
    def __init__(
        self,
        *,
        tenant: _types_pb2.Tenant | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["tenant", b"tenant"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tenant", b"tenant"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateTenantResponse: _TypeAlias = UpdateTenantResponse  # noqa: Y015

@_typing.final
class DeleteTenantRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Tenant ID (UUID). Cascades to all config versions, values, and field locks."""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteTenantRequest: _TypeAlias = DeleteTenantRequest  # noqa: Y015

@_typing.final
class DeleteTenantResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DeleteTenantResponse: _TypeAlias = DeleteTenantResponse  # noqa: Y015

@_typing.final
class LockFieldRequest(_message.Message):
    """--- Field lock requests/responses ---"""

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    FIELD_PATH_FIELD_NUMBER: _builtins.int
    LOCKED_VALUES_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    field_path: _builtins.str
    """Dot-separated field path to lock (e.g. "payments.currency")."""
    @_builtins.property
    def locked_values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """For enum fields: lock only these specific values. If empty, the
        entire field is locked regardless of value.
        """

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        field_path: _builtins.str = ...,
        locked_values: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["field_path", b"field_path", "locked_values", b"locked_values", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LockFieldRequest: _TypeAlias = LockFieldRequest  # noqa: Y015

@_typing.final
class LockFieldResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___LockFieldResponse: _TypeAlias = LockFieldResponse  # noqa: Y015

@_typing.final
class UnlockFieldRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    FIELD_PATH_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    field_path: _builtins.str
    """Dot-separated field path to unlock."""
    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        field_path: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["field_path", b"field_path", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnlockFieldRequest: _TypeAlias = UnlockFieldRequest  # noqa: Y015

@_typing.final
class UnlockFieldResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___UnlockFieldResponse: _TypeAlias = UnlockFieldResponse  # noqa: Y015

@_typing.final
class ListFieldLocksRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """Tenant ID (UUID)."""
    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListFieldLocksRequest: _TypeAlias = ListFieldLocksRequest  # noqa: Y015

@_typing.final
class ListFieldLocksResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LOCKS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def locks(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.FieldLock]:
        """All active field locks for the tenant."""

    def __init__(
        self,
        *,
        locks: _abc.Iterable[_types_pb2.FieldLock] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["locks", b"locks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListFieldLocksResponse: _TypeAlias = ListFieldLocksResponse  # noqa: Y015

@_typing.final
class ExportSchemaRequest(_message.Message):
    """--- Import/export ---"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Schema ID (UUID)."""
    version: _builtins.int
    """Schema version to export. If omitted, exports the latest version."""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        version: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "id", b"id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__version: _TypeAlias = _typing.Literal["version"]  # noqa: Y015
    _WhichOneofArgType__version: _TypeAlias = _typing.Literal["_version", b"_version"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__version) -> _WhichOneofReturnType__version | None: ...

Global___ExportSchemaRequest: _TypeAlias = ExportSchemaRequest  # noqa: Y015

@_typing.final
class ExportSchemaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    YAML_CONTENT_FIELD_NUMBER: _builtins.int
    yaml_content: _builtins.bytes
    """YAML-encoded schema (syntax v1). Includes schema name, description,
    version, and all field definitions with OAS-style constraint naming.
    Server-generated fields (id, checksum, published, created_at) are excluded.
    """
    def __init__(
        self,
        *,
        yaml_content: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["yaml_content", b"yaml_content"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExportSchemaResponse: _TypeAlias = ExportSchemaResponse  # noqa: Y015

@_typing.final
class ImportSchemaRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    YAML_CONTENT_FIELD_NUMBER: _builtins.int
    AUTO_PUBLISH_FIELD_NUMBER: _builtins.int
    yaml_content: _builtins.bytes
    """YAML-encoded schema (syntax v1). Must include `syntax`, `name`, and `fields`.

    Import uses full-replace semantics:
    - If no schema with this name exists: creates a new schema with version 1.
    - If a schema exists and fields differ from latest: creates the next version.
    - If a schema exists and fields are identical: returns AlreadyExists error.

    Imported versions are created as drafts (unpublished) unless auto_publish is true.
    The `version` field in the YAML is informational — the server assigns
    the next version number automatically.
    """
    auto_publish: _builtins.bool
    """When true, the imported version is automatically published after creation.
    If the schema already exists and fields are identical (AlreadyExists), this has no effect.
    """
    def __init__(
        self,
        *,
        yaml_content: _builtins.bytes = ...,
        auto_publish: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auto_publish", b"auto_publish", "yaml_content", b"yaml_content"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ImportSchemaRequest: _TypeAlias = ImportSchemaRequest  # noqa: Y015

@_typing.final
class ImportSchemaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCHEMA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def schema(self) -> _types_pb2.Schema:
        """The created (or existing, on AlreadyExists) schema version."""

    def __init__(
        self,
        *,
        schema: _types_pb2.Schema | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ImportSchemaResponse: _TypeAlias = ImportSchemaResponse  # noqa: Y015
