"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _FieldType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FieldTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FieldType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FIELD_TYPE_UNSPECIFIED: _FieldType.ValueType  # 0
    FIELD_TYPE_INT: _FieldType.ValueType  # 1
    """Integer value. Encoded as a decimal string (e.g. "42", "-1").
    Supports minimum/maximum constraints on the numeric value.
    """
    FIELD_TYPE_STRING: _FieldType.ValueType  # 2
    """Free-form string value.
    Supports minimum/maximum constraints on string length, pattern (regex),
    and enum constraints.
    """
    FIELD_TYPE_TIME: _FieldType.ValueType  # 3
    """Timestamp value. Encoded as an RFC 3339 string (e.g. "2025-01-15T09:30:00Z")."""
    FIELD_TYPE_DURATION: _FieldType.ValueType  # 4
    """Duration value. Encoded as a Go-style duration string (e.g. "24h", "30m", "500ms").
    Supports minimum/maximum constraints on the duration in seconds.
    """
    FIELD_TYPE_URL: _FieldType.ValueType  # 5
    """URL value. Must be a valid absolute URL."""
    FIELD_TYPE_JSON: _FieldType.ValueType  # 6
    """JSON value. Stored as a JSON-encoded string.
    Supports json_schema constraint for structural validation.
    """
    FIELD_TYPE_NUMBER: _FieldType.ValueType  # 7
    """Floating-point number value. Encoded as a decimal string (e.g. "3.14", "0.025").
    Supports minimum/maximum constraints on the numeric value.
    """
    FIELD_TYPE_BOOL: _FieldType.ValueType  # 8
    """Boolean value. Encoded as "true" or "false"."""

class FieldType(_FieldType, metaclass=_FieldTypeEnumTypeWrapper):
    """FieldType enumerates the supported configuration value types.
    Each type maps to a specific field in the TypedValue oneof.
    """

FIELD_TYPE_UNSPECIFIED: FieldType.ValueType  # 0
FIELD_TYPE_INT: FieldType.ValueType  # 1
"""Integer value. Encoded as a decimal string (e.g. "42", "-1").
Supports minimum/maximum constraints on the numeric value.
"""
FIELD_TYPE_STRING: FieldType.ValueType  # 2
"""Free-form string value.
Supports minimum/maximum constraints on string length, pattern (regex),
and enum constraints.
"""
FIELD_TYPE_TIME: FieldType.ValueType  # 3
"""Timestamp value. Encoded as an RFC 3339 string (e.g. "2025-01-15T09:30:00Z")."""
FIELD_TYPE_DURATION: FieldType.ValueType  # 4
"""Duration value. Encoded as a Go-style duration string (e.g. "24h", "30m", "500ms").
Supports minimum/maximum constraints on the duration in seconds.
"""
FIELD_TYPE_URL: FieldType.ValueType  # 5
"""URL value. Must be a valid absolute URL."""
FIELD_TYPE_JSON: FieldType.ValueType  # 6
"""JSON value. Stored as a JSON-encoded string.
Supports json_schema constraint for structural validation.
"""
FIELD_TYPE_NUMBER: FieldType.ValueType  # 7
"""Floating-point number value. Encoded as a decimal string (e.g. "3.14", "0.025").
Supports minimum/maximum constraints on the numeric value.
"""
FIELD_TYPE_BOOL: FieldType.ValueType  # 8
"""Boolean value. Encoded as "true" or "false"."""
Global___FieldType: _TypeAlias = FieldType  # noqa: Y015

@_typing.final
class FieldConstraints(_message.Message):
    """FieldConstraints defines validation rules for a schema field.
    Which constraints apply depends on the field's type — see FieldType docs.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MIN_FIELD_NUMBER: _builtins.int
    MAX_FIELD_NUMBER: _builtins.int
    REGEX_FIELD_NUMBER: _builtins.int
    ENUM_VALUES_FIELD_NUMBER: _builtins.int
    JSON_SCHEMA_FIELD_NUMBER: _builtins.int
    EXCLUSIVE_MIN_FIELD_NUMBER: _builtins.int
    EXCLUSIVE_MAX_FIELD_NUMBER: _builtins.int
    MIN_LENGTH_FIELD_NUMBER: _builtins.int
    MAX_LENGTH_FIELD_NUMBER: _builtins.int
    min: _builtins.float
    """For integer/number/duration: minimum allowed value (inclusive, >=)."""
    max: _builtins.float
    """For integer/number/duration: maximum allowed value (inclusive, <=)."""
    regex: _builtins.str
    """Regular expression pattern the value must match.
    Applies to string-typed fields. Uses RE2 syntax.
    """
    json_schema: _builtins.str
    """JSON Schema document for structural validation of json-typed fields.
    Encoded as a JSON string.
    """
    exclusive_min: _builtins.float
    """For integer/number/duration: exclusive minimum (strict, >)."""
    exclusive_max: _builtins.float
    """For integer/number/duration: exclusive maximum (strict, <)."""
    min_length: _builtins.int
    """For string: minimum allowed length."""
    max_length: _builtins.int
    """For string: maximum allowed length."""
    @_builtins.property
    def enum_values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Allowed values. If non-empty, the value must be one of these.
        Applies to any field type.
        """

    def __init__(
        self,
        *,
        min: _builtins.float | None = ...,
        max: _builtins.float | None = ...,
        regex: _builtins.str | None = ...,
        enum_values: _abc.Iterable[_builtins.str] | None = ...,
        json_schema: _builtins.str | None = ...,
        exclusive_min: _builtins.float | None = ...,
        exclusive_max: _builtins.float | None = ...,
        min_length: _builtins.int | None = ...,
        max_length: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_exclusive_max", b"_exclusive_max", "_exclusive_min", b"_exclusive_min", "_json_schema", b"_json_schema", "_max", b"_max", "_max_length", b"_max_length", "_min", b"_min", "_min_length", b"_min_length", "_regex", b"_regex", "exclusive_max", b"exclusive_max", "exclusive_min", b"exclusive_min", "json_schema", b"json_schema", "max", b"max", "max_length", b"max_length", "min", b"min", "min_length", b"min_length", "regex", b"regex"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_exclusive_max", b"_exclusive_max", "_exclusive_min", b"_exclusive_min", "_json_schema", b"_json_schema", "_max", b"_max", "_max_length", b"_max_length", "_min", b"_min", "_min_length", b"_min_length", "_regex", b"_regex", "enum_values", b"enum_values", "exclusive_max", b"exclusive_max", "exclusive_min", b"exclusive_min", "json_schema", b"json_schema", "max", b"max", "max_length", b"max_length", "min", b"min", "min_length", b"min_length", "regex", b"regex"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__exclusive_max: _TypeAlias = _typing.Literal["exclusive_max"]  # noqa: Y015
    _WhichOneofArgType__exclusive_max: _TypeAlias = _typing.Literal["_exclusive_max", b"_exclusive_max"]  # noqa: Y015
    _WhichOneofReturnType__exclusive_min: _TypeAlias = _typing.Literal["exclusive_min"]  # noqa: Y015
    _WhichOneofArgType__exclusive_min: _TypeAlias = _typing.Literal["_exclusive_min", b"_exclusive_min"]  # noqa: Y015
    _WhichOneofReturnType__json_schema: _TypeAlias = _typing.Literal["json_schema"]  # noqa: Y015
    _WhichOneofArgType__json_schema: _TypeAlias = _typing.Literal["_json_schema", b"_json_schema"]  # noqa: Y015
    _WhichOneofReturnType__max: _TypeAlias = _typing.Literal["max"]  # noqa: Y015
    _WhichOneofArgType__max: _TypeAlias = _typing.Literal["_max", b"_max"]  # noqa: Y015
    _WhichOneofReturnType__max_length: _TypeAlias = _typing.Literal["max_length"]  # noqa: Y015
    _WhichOneofArgType__max_length: _TypeAlias = _typing.Literal["_max_length", b"_max_length"]  # noqa: Y015
    _WhichOneofReturnType__min: _TypeAlias = _typing.Literal["min"]  # noqa: Y015
    _WhichOneofArgType__min: _TypeAlias = _typing.Literal["_min", b"_min"]  # noqa: Y015
    _WhichOneofReturnType__min_length: _TypeAlias = _typing.Literal["min_length"]  # noqa: Y015
    _WhichOneofArgType__min_length: _TypeAlias = _typing.Literal["_min_length", b"_min_length"]  # noqa: Y015
    _WhichOneofReturnType__regex: _TypeAlias = _typing.Literal["regex"]  # noqa: Y015
    _WhichOneofArgType__regex: _TypeAlias = _typing.Literal["_regex", b"_regex"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__exclusive_max) -> _WhichOneofReturnType__exclusive_max | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__exclusive_min) -> _WhichOneofReturnType__exclusive_min | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__json_schema) -> _WhichOneofReturnType__json_schema | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max) -> _WhichOneofReturnType__max | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_length) -> _WhichOneofReturnType__max_length | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__min) -> _WhichOneofReturnType__min | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__min_length) -> _WhichOneofReturnType__min_length | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__regex) -> _WhichOneofReturnType__regex | None: ...

Global___FieldConstraints: _TypeAlias = FieldConstraints  # noqa: Y015

@_typing.final
class SchemaField(_message.Message):
    """SchemaField defines a single field within a configuration schema."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ExamplesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___FieldExample: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___FieldExample | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PATH_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    CONSTRAINTS_FIELD_NUMBER: _builtins.int
    NULLABLE_FIELD_NUMBER: _builtins.int
    DEPRECATED_FIELD_NUMBER: _builtins.int
    REDIRECT_TO_FIELD_NUMBER: _builtins.int
    DEFAULT_VALUE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    EXAMPLE_FIELD_NUMBER: _builtins.int
    EXAMPLES_FIELD_NUMBER: _builtins.int
    EXTERNAL_DOCS_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    READ_ONLY_FIELD_NUMBER: _builtins.int
    WRITE_ONCE_FIELD_NUMBER: _builtins.int
    SENSITIVE_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    """Dot-separated hierarchical path (e.g. "payments.settlement.window").
    Must be unique within a schema version.
    """
    type: Global___FieldType.ValueType
    """The value type for this field. Controls validation behavior."""
    nullable: _builtins.bool
    """Whether this field accepts empty/null values."""
    deprecated: _builtins.bool
    """Whether this field is deprecated. Deprecated fields are still readable
    but clients should migrate to redirect_to if set.
    """
    redirect_to: _builtins.str
    """When deprecated, reads of this field can be redirected to this path."""
    default_value: _builtins.str
    """Default value for this field, encoded as a string matching the field type."""
    description: _builtins.str
    """Human-readable description of the field's purpose."""
    title: _builtins.str
    """Human-friendly display name (e.g. "Fee Rate" for path "payments.fee_rate").
    OAS: title
    """
    example: _builtins.str
    """Single example value, encoded as a string matching the field type.
    OAS: example
    """
    format: _builtins.str
    """Semantic format hint within the base type (e.g. "email", "semver", "percentage").
    Informational — not enforced by validation.
    OAS: format
    """
    read_only: _builtins.bool
    """Whether this field is system-managed and not user-editable.
    OAS: readOnly
    """
    write_once: _builtins.bool
    """Whether this field can only be set once and becomes immutable after."""
    sensitive: _builtins.bool
    """Whether this field's value should be masked in logs and UI."""
    @_builtins.property
    def constraints(self) -> Global___FieldConstraints:
        """Validation constraints. Optional — when absent, any value of the
        correct type is accepted.
        """

    @_builtins.property
    def examples(self) -> _containers.MessageMap[_builtins.str, Global___FieldExample]:
        """Named examples with optional summary. Key is example name.
        OAS: examples
        """

    @_builtins.property
    def external_docs(self) -> Global___ExternalDocs:
        """Link to external documentation for this field.
        OAS: externalDocs
        """

    @_builtins.property
    def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Tags for grouping and categorization beyond the dot-prefix hierarchy.
        OAS: x-tags
        """

    def __init__(
        self,
        *,
        path: _builtins.str = ...,
        type: Global___FieldType.ValueType = ...,
        constraints: Global___FieldConstraints | None = ...,
        nullable: _builtins.bool = ...,
        deprecated: _builtins.bool = ...,
        redirect_to: _builtins.str | None = ...,
        default_value: _builtins.str | None = ...,
        description: _builtins.str | None = ...,
        title: _builtins.str | None = ...,
        example: _builtins.str | None = ...,
        examples: _abc.Mapping[_builtins.str, Global___FieldExample] | None = ...,
        external_docs: Global___ExternalDocs | None = ...,
        tags: _abc.Iterable[_builtins.str] | None = ...,
        format: _builtins.str | None = ...,
        read_only: _builtins.bool = ...,
        write_once: _builtins.bool = ...,
        sensitive: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_default_value", b"_default_value", "_description", b"_description", "_example", b"_example", "_format", b"_format", "_redirect_to", b"_redirect_to", "_title", b"_title", "constraints", b"constraints", "default_value", b"default_value", "description", b"description", "example", b"example", "external_docs", b"external_docs", "format", b"format", "redirect_to", b"redirect_to", "title", b"title"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_default_value", b"_default_value", "_description", b"_description", "_example", b"_example", "_format", b"_format", "_redirect_to", b"_redirect_to", "_title", b"_title", "constraints", b"constraints", "default_value", b"default_value", "deprecated", b"deprecated", "description", b"description", "example", b"example", "examples", b"examples", "external_docs", b"external_docs", "format", b"format", "nullable", b"nullable", "path", b"path", "read_only", b"read_only", "redirect_to", b"redirect_to", "sensitive", b"sensitive", "tags", b"tags", "title", b"title", "type", b"type", "write_once", b"write_once"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__default_value: _TypeAlias = _typing.Literal["default_value"]  # noqa: Y015
    _WhichOneofArgType__default_value: _TypeAlias = _typing.Literal["_default_value", b"_default_value"]  # noqa: Y015
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    _WhichOneofReturnType__example: _TypeAlias = _typing.Literal["example"]  # noqa: Y015
    _WhichOneofArgType__example: _TypeAlias = _typing.Literal["_example", b"_example"]  # noqa: Y015
    _WhichOneofReturnType__format: _TypeAlias = _typing.Literal["format"]  # noqa: Y015
    _WhichOneofArgType__format: _TypeAlias = _typing.Literal["_format", b"_format"]  # noqa: Y015
    _WhichOneofReturnType__redirect_to: _TypeAlias = _typing.Literal["redirect_to"]  # noqa: Y015
    _WhichOneofArgType__redirect_to: _TypeAlias = _typing.Literal["_redirect_to", b"_redirect_to"]  # noqa: Y015
    _WhichOneofReturnType__title: _TypeAlias = _typing.Literal["title"]  # noqa: Y015
    _WhichOneofArgType__title: _TypeAlias = _typing.Literal["_title", b"_title"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__default_value) -> _WhichOneofReturnType__default_value | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__example) -> _WhichOneofReturnType__example | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__format) -> _WhichOneofReturnType__format | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__redirect_to) -> _WhichOneofReturnType__redirect_to | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__title) -> _WhichOneofReturnType__title | None: ...

Global___SchemaField: _TypeAlias = SchemaField  # noqa: Y015

@_typing.final
class FieldExample(_message.Message):
    """FieldExample represents a named example value for a schema field."""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    SUMMARY_FIELD_NUMBER: _builtins.int
    value: _builtins.str
    """The example value, encoded as a string matching the field type."""
    summary: _builtins.str
    """Short description of what this example demonstrates."""
    def __init__(
        self,
        *,
        value: _builtins.str = ...,
        summary: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["summary", b"summary", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FieldExample: _TypeAlias = FieldExample  # noqa: Y015

@_typing.final
class ExternalDocs(_message.Message):
    """ExternalDocs links to external documentation.
    OAS: External Documentation Object
    """

    DESCRIPTOR: _descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    description: _builtins.str
    """Human-readable description of the external documentation."""
    url: _builtins.str
    """URL to the external documentation."""
    def __init__(
        self,
        *,
        description: _builtins.str = ...,
        url: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExternalDocs: _TypeAlias = ExternalDocs  # noqa: Y015

@_typing.final
class SchemaInfo(_message.Message):
    """SchemaInfo contains optional metadata about a schema's ownership and context.
    OAS: Info Object
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class LabelsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TITLE_FIELD_NUMBER: _builtins.int
    AUTHOR_FIELD_NUMBER: _builtins.int
    CONTACT_FIELD_NUMBER: _builtins.int
    LABELS_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    """Human-friendly display title for the schema.
    OAS: info.title
    """
    author: _builtins.str
    """Schema owner identifier (person, team, or service)."""
    @_builtins.property
    def contact(self) -> Global___SchemaContact:
        """Contact information for the schema owner.
        OAS: info.contact
        """

    @_builtins.property
    def labels(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Key-value labels for filtering and categorization."""

    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        author: _builtins.str = ...,
        contact: Global___SchemaContact | None = ...,
        labels: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["contact", b"contact"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["author", b"author", "contact", b"contact", "labels", b"labels", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SchemaInfo: _TypeAlias = SchemaInfo  # noqa: Y015

@_typing.final
class SchemaContact(_message.Message):
    """SchemaContact contains contact information for a schema owner.
    OAS: Contact Object
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Contact name (person or team)."""
    email: _builtins.str
    """Contact email address."""
    url: _builtins.str
    """Contact URL (e.g. team wiki page)."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        email: _builtins.str = ...,
        url: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "name", b"name", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SchemaContact: _TypeAlias = SchemaContact  # noqa: Y015

@_typing.final
class Schema(_message.Message):
    """Schema represents a configuration schema template.
    Schemas define the allowed fields and their types for tenant configurations.
    Each schema is versioned — updates create new immutable versions.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    PARENT_VERSION_FIELD_NUMBER: _builtins.int
    VERSION_DESCRIPTION_FIELD_NUMBER: _builtins.int
    CHECKSUM_FIELD_NUMBER: _builtins.int
    PUBLISHED_FIELD_NUMBER: _builtins.int
    FIELDS_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Server-assigned unique identifier (UUID)."""
    name: _builtins.str
    """Unique name for this schema. Must be a valid slug: lowercase alphanumeric
    characters and hyphens, 1-63 characters, matching [a-z0-9]([a-z0-9-]*[a-z0-9])?.
    """
    description: _builtins.str
    """Human-readable description of the schema's purpose."""
    version: _builtins.int
    """Schema version number (monotonically increasing, starting at 1)."""
    parent_version: _builtins.int
    """The version this was derived from. Absent for the initial version (v1)."""
    version_description: _builtins.str
    """Description of what changed in this version."""
    checksum: _builtins.str
    """Deterministic checksum of the field definitions (type, constraints, path).
    Used for change detection on import.
    """
    published: _builtins.bool
    """Whether this version is published. Only published versions can be
    assigned to tenants. Published versions are immutable.
    """
    @_builtins.property
    def fields(self) -> _containers.RepeatedCompositeFieldContainer[Global___SchemaField]:
        """The fields defined in this schema version."""

    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp:
        """When this version was created."""

    @_builtins.property
    def info(self) -> Global___SchemaInfo:
        """Optional schema metadata: ownership, contact, labels."""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        version: _builtins.int = ...,
        parent_version: _builtins.int | None = ...,
        version_description: _builtins.str = ...,
        checksum: _builtins.str = ...,
        published: _builtins.bool = ...,
        fields: _abc.Iterable[Global___SchemaField] | None = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        info: Global___SchemaInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_parent_version", b"_parent_version", "created_at", b"created_at", "info", b"info", "parent_version", b"parent_version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_parent_version", b"_parent_version", "checksum", b"checksum", "created_at", b"created_at", "description", b"description", "fields", b"fields", "id", b"id", "info", b"info", "name", b"name", "parent_version", b"parent_version", "published", b"published", "version", b"version", "version_description", b"version_description"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__parent_version: _TypeAlias = _typing.Literal["parent_version"]  # noqa: Y015
    _WhichOneofArgType__parent_version: _TypeAlias = _typing.Literal["_parent_version", b"_parent_version"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__parent_version) -> _WhichOneofReturnType__parent_version | None: ...

Global___Schema: _TypeAlias = Schema  # noqa: Y015

@_typing.final
class Tenant(_message.Message):
    """Tenant represents an organization or entity that has its own configuration
    based on an assigned schema version.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SCHEMA_ID_FIELD_NUMBER: _builtins.int
    SCHEMA_VERSION_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Server-assigned unique identifier (UUID)."""
    name: _builtins.str
    """Unique name for this tenant. Must be a valid slug: lowercase alphanumeric
    characters and hyphens, 1-63 characters, matching [a-z0-9]([a-z0-9-]*[a-z0-9])?.
    """
    schema_id: _builtins.str
    """The schema this tenant's configuration is based on (UUID)."""
    schema_version: _builtins.int
    """The specific schema version assigned to this tenant.
    Must reference a published schema version.
    """
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp:
        """When the tenant was created."""

    @_builtins.property
    def updated_at(self) -> _timestamp_pb2.Timestamp:
        """When the tenant was last updated (name or schema version change)."""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        schema_id: _builtins.str = ...,
        schema_version: _builtins.int = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        updated_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "id", b"id", "name", b"name", "schema_id", b"schema_id", "schema_version", b"schema_version", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Tenant: _TypeAlias = Tenant  # noqa: Y015

@_typing.final
class FieldLock(_message.Message):
    """FieldLock prevents a configuration field from being modified by non-superadmin users.
    Superadmins bypass all field locks.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    FIELD_PATH_FIELD_NUMBER: _builtins.int
    LOCKED_VALUES_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """The tenant this lock applies to (UUID)."""
    field_path: _builtins.str
    """The dot-separated field path that is locked."""
    @_builtins.property
    def locked_values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """For enum fields: the specific subset of values that are locked
        (not editable by admin). If empty, the entire field is locked.
        """

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        field_path: _builtins.str = ...,
        locked_values: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["field_path", b"field_path", "locked_values", b"locked_values", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FieldLock: _TypeAlias = FieldLock  # noqa: Y015

@_typing.final
class TypedValue(_message.Message):
    """TypedValue holds a configuration value with its native type.
    An unset oneof (no field present) represents a null value.
    """

    DESCRIPTOR: _descriptor.Descriptor

    INTEGER_VALUE_FIELD_NUMBER: _builtins.int
    NUMBER_VALUE_FIELD_NUMBER: _builtins.int
    STRING_VALUE_FIELD_NUMBER: _builtins.int
    BOOL_VALUE_FIELD_NUMBER: _builtins.int
    TIME_VALUE_FIELD_NUMBER: _builtins.int
    DURATION_VALUE_FIELD_NUMBER: _builtins.int
    URL_VALUE_FIELD_NUMBER: _builtins.int
    JSON_VALUE_FIELD_NUMBER: _builtins.int
    integer_value: _builtins.int
    """Integer value."""
    number_value: _builtins.float
    """Floating-point number value."""
    string_value: _builtins.str
    """Free-form string value."""
    bool_value: _builtins.bool
    """Boolean value."""
    url_value: _builtins.str
    """URL value (must be a valid absolute URL)."""
    json_value: _builtins.str
    """JSON value (must be valid JSON)."""
    @_builtins.property
    def time_value(self) -> _timestamp_pb2.Timestamp:
        """Timestamp value."""

    @_builtins.property
    def duration_value(self) -> _duration_pb2.Duration:
        """Duration value."""

    def __init__(
        self,
        *,
        integer_value: _builtins.int = ...,
        number_value: _builtins.float = ...,
        string_value: _builtins.str = ...,
        bool_value: _builtins.bool = ...,
        time_value: _timestamp_pb2.Timestamp | None = ...,
        duration_value: _duration_pb2.Duration | None = ...,
        url_value: _builtins.str = ...,
        json_value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "duration_value", b"duration_value", "integer_value", b"integer_value", "json_value", b"json_value", "kind", b"kind", "number_value", b"number_value", "string_value", b"string_value", "time_value", b"time_value", "url_value", b"url_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "duration_value", b"duration_value", "integer_value", b"integer_value", "json_value", b"json_value", "kind", b"kind", "number_value", b"number_value", "string_value", b"string_value", "time_value", b"time_value", "url_value", b"url_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["integer_value", "number_value", "string_value", "bool_value", "time_value", "duration_value", "url_value", "json_value"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___TypedValue: _TypeAlias = TypedValue  # noqa: Y015

@_typing.final
class ConfigValue(_message.Message):
    """ConfigValue represents a single configuration value at a point in time."""

    DESCRIPTOR: _descriptor.Descriptor

    FIELD_PATH_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    CHECKSUM_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    field_path: _builtins.str
    """Dot-separated field path (e.g. "payments.fee")."""
    checksum: _builtins.str
    """Checksum of the value (xxHash). Used for optimistic concurrency control
    in SetField/SetFields via expected_checksum.
    """
    description: _builtins.str
    """Human-readable description explaining this specific value.
    Only populated when include_description(s) is true in the request.
    """
    @_builtins.property
    def value(self) -> Global___TypedValue:
        """The typed value. Absent when the field value is null."""

    def __init__(
        self,
        *,
        field_path: _builtins.str = ...,
        value: Global___TypedValue | None = ...,
        checksum: _builtins.str = ...,
        description: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "checksum", b"checksum", "description", b"description", "field_path", b"field_path", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...

Global___ConfigValue: _TypeAlias = ConfigValue  # noqa: Y015

@_typing.final
class ConfigVersion(_message.Message):
    """ConfigVersion represents a point-in-time snapshot of configuration changes.
    Each write operation (SetField, SetFields, RollbackToVersion) creates a new
    config version. Versions store only the changed fields (delta storage) — the
    full config at any version is the union of all deltas up to that version.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TENANT_ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    CREATED_BY_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Server-assigned unique identifier (UUID)."""
    tenant_id: _builtins.str
    """The tenant this version belongs to (UUID)."""
    version: _builtins.int
    """Version number (monotonically increasing, starting at 1)."""
    description: _builtins.str
    """Description of what changed in this version."""
    created_by: _builtins.str
    """The actor who created this version (from JWT subject, or "unknown" if auth is disabled)."""
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp:
        """When this version was created."""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        tenant_id: _builtins.str = ...,
        version: _builtins.int = ...,
        description: _builtins.str = ...,
        created_by: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "created_by", b"created_by", "description", b"description", "id", b"id", "tenant_id", b"tenant_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConfigVersion: _TypeAlias = ConfigVersion  # noqa: Y015

@_typing.final
class Config(_message.Message):
    """Config represents the full resolved configuration for a tenant at a specific version."""

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    VALUES_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """The tenant this config belongs to (UUID)."""
    version: _builtins.int
    """The version number this config was resolved at."""
    @_builtins.property
    def values(self) -> _containers.RepeatedCompositeFieldContainer[Global___ConfigValue]:
        """All configuration values at this version."""

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        version: _builtins.int = ...,
        values: _abc.Iterable[Global___ConfigValue] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tenant_id", b"tenant_id", "values", b"values", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015

@_typing.final
class ConfigChange(_message.Message):
    """ConfigChange represents a real-time change event pushed to subscribers
    via the Subscribe streaming RPC.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    FIELD_PATH_FIELD_NUMBER: _builtins.int
    OLD_VALUE_FIELD_NUMBER: _builtins.int
    NEW_VALUE_FIELD_NUMBER: _builtins.int
    CHANGED_BY_FIELD_NUMBER: _builtins.int
    CHANGED_AT_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """The tenant whose config changed (UUID)."""
    version: _builtins.int
    """The new config version number created by this change."""
    field_path: _builtins.str
    """The field that was changed."""
    changed_by: _builtins.str
    """The actor who made the change."""
    @_builtins.property
    def old_value(self) -> Global___TypedValue:
        """The previous value. Absent if field was newly created or was null."""

    @_builtins.property
    def new_value(self) -> Global___TypedValue:
        """The new value. Absent if field was set to null."""

    @_builtins.property
    def changed_at(self) -> _timestamp_pb2.Timestamp:
        """When the change occurred."""

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        version: _builtins.int = ...,
        field_path: _builtins.str = ...,
        old_value: Global___TypedValue | None = ...,
        new_value: Global___TypedValue | None = ...,
        changed_by: _builtins.str = ...,
        changed_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["changed_at", b"changed_at", "new_value", b"new_value", "old_value", b"old_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["changed_at", b"changed_at", "changed_by", b"changed_by", "field_path", b"field_path", "new_value", b"new_value", "old_value", b"old_value", "tenant_id", b"tenant_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConfigChange: _TypeAlias = ConfigChange  # noqa: Y015

@_typing.final
class AuditEntry(_message.Message):
    """AuditEntry represents a write event recorded in the audit log.
    Every config mutation (SetField, SetFields, RollbackToVersion) creates
    one or more audit entries atomically with the config change.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TENANT_ID_FIELD_NUMBER: _builtins.int
    ACTOR_FIELD_NUMBER: _builtins.int
    ACTION_FIELD_NUMBER: _builtins.int
    FIELD_PATH_FIELD_NUMBER: _builtins.int
    OLD_VALUE_FIELD_NUMBER: _builtins.int
    NEW_VALUE_FIELD_NUMBER: _builtins.int
    CONFIG_VERSION_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Server-assigned unique identifier (UUID)."""
    tenant_id: _builtins.str
    """The tenant affected (UUID)."""
    actor: _builtins.str
    """The actor who performed the action (from JWT subject)."""
    action: _builtins.str
    """The action type (e.g. "set_field", "rollback")."""
    field_path: _builtins.str
    """The field that was changed. Present for set_field actions."""
    old_value: _builtins.str
    """The previous value. Present for set_field actions."""
    new_value: _builtins.str
    """The new value. Present for set_field actions.
    For rollback actions, contains the target version (e.g. "v2").
    """
    config_version: _builtins.int
    """The config version number created by this action."""
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp:
        """When the audit entry was created."""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        tenant_id: _builtins.str = ...,
        actor: _builtins.str = ...,
        action: _builtins.str = ...,
        field_path: _builtins.str | None = ...,
        old_value: _builtins.str | None = ...,
        new_value: _builtins.str | None = ...,
        config_version: _builtins.int | None = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_config_version", b"_config_version", "_field_path", b"_field_path", "_new_value", b"_new_value", "_old_value", b"_old_value", "config_version", b"config_version", "created_at", b"created_at", "field_path", b"field_path", "new_value", b"new_value", "old_value", b"old_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_config_version", b"_config_version", "_field_path", b"_field_path", "_new_value", b"_new_value", "_old_value", b"_old_value", "action", b"action", "actor", b"actor", "config_version", b"config_version", "created_at", b"created_at", "field_path", b"field_path", "id", b"id", "new_value", b"new_value", "old_value", b"old_value", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__config_version: _TypeAlias = _typing.Literal["config_version"]  # noqa: Y015
    _WhichOneofArgType__config_version: _TypeAlias = _typing.Literal["_config_version", b"_config_version"]  # noqa: Y015
    _WhichOneofReturnType__field_path: _TypeAlias = _typing.Literal["field_path"]  # noqa: Y015
    _WhichOneofArgType__field_path: _TypeAlias = _typing.Literal["_field_path", b"_field_path"]  # noqa: Y015
    _WhichOneofReturnType__new_value: _TypeAlias = _typing.Literal["new_value"]  # noqa: Y015
    _WhichOneofArgType__new_value: _TypeAlias = _typing.Literal["_new_value", b"_new_value"]  # noqa: Y015
    _WhichOneofReturnType__old_value: _TypeAlias = _typing.Literal["old_value"]  # noqa: Y015
    _WhichOneofArgType__old_value: _TypeAlias = _typing.Literal["_old_value", b"_old_value"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__config_version) -> _WhichOneofReturnType__config_version | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__field_path) -> _WhichOneofReturnType__field_path | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__new_value) -> _WhichOneofReturnType__new_value | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__old_value) -> _WhichOneofReturnType__old_value | None: ...

Global___AuditEntry: _TypeAlias = AuditEntry  # noqa: Y015

@_typing.final
class UsageStats(_message.Message):
    """UsageStats represents aggregated read usage statistics for a config field."""

    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    FIELD_PATH_FIELD_NUMBER: _builtins.int
    READ_COUNT_FIELD_NUMBER: _builtins.int
    LAST_READ_BY_FIELD_NUMBER: _builtins.int
    LAST_READ_AT_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.str
    """The tenant (UUID)."""
    field_path: _builtins.str
    """The field path."""
    read_count: _builtins.int
    """Total number of reads across the queried time range."""
    last_read_by: _builtins.str
    """The last actor who read this field (if tracked)."""
    @_builtins.property
    def last_read_at(self) -> _timestamp_pb2.Timestamp:
        """When this field was last read (if tracked)."""

    def __init__(
        self,
        *,
        tenant_id: _builtins.str = ...,
        field_path: _builtins.str = ...,
        read_count: _builtins.int = ...,
        last_read_by: _builtins.str | None = ...,
        last_read_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_last_read_at", b"_last_read_at", "_last_read_by", b"_last_read_by", "last_read_at", b"last_read_at", "last_read_by", b"last_read_by"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_last_read_at", b"_last_read_at", "_last_read_by", b"_last_read_by", "field_path", b"field_path", "last_read_at", b"last_read_at", "last_read_by", b"last_read_by", "read_count", b"read_count", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__last_read_at: _TypeAlias = _typing.Literal["last_read_at"]  # noqa: Y015
    _WhichOneofArgType__last_read_at: _TypeAlias = _typing.Literal["_last_read_at", b"_last_read_at"]  # noqa: Y015
    _WhichOneofReturnType__last_read_by: _TypeAlias = _typing.Literal["last_read_by"]  # noqa: Y015
    _WhichOneofArgType__last_read_by: _TypeAlias = _typing.Literal["_last_read_by", b"_last_read_by"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__last_read_at) -> _WhichOneofReturnType__last_read_at | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__last_read_by) -> _WhichOneofReturnType__last_read_by | None: ...

Global___UsageStats: _TypeAlias = UsageStats  # noqa: Y015
