# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from centralconfig.v1 import version_service_pb2 as centralconfig_dot_v1_dot_version__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in centralconfig/v1/version_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VersionServiceStub(object):
    """VersionService provides server version information.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerVersion = channel.unary_unary(
                '/centralconfig.v1.VersionService/GetServerVersion',
                request_serializer=centralconfig_dot_v1_dot_version__service__pb2.GetServerVersionRequest.SerializeToString,
                response_deserializer=centralconfig_dot_v1_dot_version__service__pb2.GetServerVersionResponse.FromString,
                _registered_method=True)


class VersionServiceServicer(object):
    """VersionService provides server version information.
    """

    def GetServerVersion(self, request, context):
        """GetServerVersion returns the server's build version and commit hash.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VersionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerVersion,
                    request_deserializer=centralconfig_dot_v1_dot_version__service__pb2.GetServerVersionRequest.FromString,
                    response_serializer=centralconfig_dot_v1_dot_version__service__pb2.GetServerVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'centralconfig.v1.VersionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('centralconfig.v1.VersionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VersionService(object):
    """VersionService provides server version information.
    """

    @staticmethod
    def GetServerVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centralconfig.v1.VersionService/GetServerVersion',
            centralconfig_dot_v1_dot_version__service__pb2.GetServerVersionRequest.SerializeToString,
            centralconfig_dot_v1_dot_version__service__pb2.GetServerVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
