"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetServerVersionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetServerVersionRequest: _TypeAlias = GetServerVersionRequest  # noqa: Y015

@_typing.final
class GetServerVersionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    version: _builtins.str
    """Semantic version string (e.g. "1.2.3" or "dev")."""
    commit: _builtins.str
    """Git commit hash."""
    def __init__(
        self,
        *,
        version: _builtins.str = ...,
        commit: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetServerVersionResponse: _TypeAlias = GetServerVersionResponse  # noqa: Y015
