# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: centralconfig/v1/version_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'centralconfig/v1/version_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&centralconfig/v1/version_service.proto\x12\x10\x63\x65ntralconfig.v1\x1a\x1cgoogle/api/annotations.proto\"\x19\n\x17GetServerVersionRequest\";\n\x18GetServerVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\t2\x90\x01\n\x0eVersionService\x12~\n\x10GetServerVersion\x12).centralconfig.v1.GetServerVersionRequest\x1a*.centralconfig.v1.GetServerVersionResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\x0b/v1/versionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'centralconfig.v1.version_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSIONSERVICE'].methods_by_name['GetServerVersion']._loaded_options = None
  _globals['_VERSIONSERVICE'].methods_by_name['GetServerVersion']._serialized_options = b'\202\323\344\223\002\r\022\013/v1/version'
  _globals['_GETSERVERVERSIONREQUEST']._serialized_start=90
  _globals['_GETSERVERVERSIONREQUEST']._serialized_end=115
  _globals['_GETSERVERVERSIONRESPONSE']._serialized_start=117
  _globals['_GETSERVERVERSIONRESPONSE']._serialized_end=176
  _globals['_VERSIONSERVICE']._serialized_start=179
  _globals['_VERSIONSERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
