"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from centralconfig.v1 import version_service_pb2 as _version_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class VersionServiceStub:
    """VersionService provides server version information."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> VersionServiceAsyncStub: ...
    GetServerVersion: _grpc.UnaryUnaryMultiCallable[_version_service_pb2.GetServerVersionRequest, _version_service_pb2.GetServerVersionResponse]
    """GetServerVersion returns the server's build version and commit hash."""

@_typing.type_check_only
class VersionServiceAsyncStub(VersionServiceStub):
    """VersionService provides server version information."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetServerVersion: _aio.UnaryUnaryMultiCallable[_version_service_pb2.GetServerVersionRequest, _version_service_pb2.GetServerVersionResponse]  # type: ignore[assignment]
    """GetServerVersion returns the server's build version and commit hash."""

class VersionServiceServicer(metaclass=_abc_1.ABCMeta):
    """VersionService provides server version information."""

    @_abc_1.abstractmethod
    def GetServerVersion(
        self,
        request: _version_service_pb2.GetServerVersionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_version_service_pb2.GetServerVersionResponse, _abc.Awaitable[_version_service_pb2.GetServerVersionResponse]]:
        """GetServerVersion returns the server's build version and commit hash."""

def add_VersionServiceServicer_to_server(servicer: VersionServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
