name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install build
      - run: cd sdk && python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: sdk/dist/
          print-hash: true
